// Room 8 - Class 801 Live Survey Data (names-only public snapshot; PINs live server-side)
window.CLASS_801_DATA = [
  {
    "first_name": "Ruby",
    "last_name": "Cook",
    "has_submitted": false,
    "task": "Active / Logged In",
    "email": "",
    "pronouns": "",
    "phonetic": "",
    "transit": "",
    "peers": "",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {},
    "formats": []
  },
  {
    "first_name": "Talia",
    "last_name": "David",
    "has_submitted": false,
    "task": "Active / Logged In",
    "email": "",
    "pronouns": "",
    "phonetic": "",
    "transit": "",
    "peers": "",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {},
    "formats": []
  },
  {
    "first_name": "Jason",
    "last_name": "Desveaux",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "djm568510@gnspes.ca",
    "pronouns": "him",
    "phonetic": "Jason Desveaux",
    "transit": "",
    "peers": "",
    "curious": "i dont know",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "i need to sit next to steven",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Brief",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Deep",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Deep",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Deep",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Deep",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Over-Covered"
    },
    "formats": []
  },
  {
    "first_name": "Mae'ijah",
    "last_name": "Downey",
    "has_submitted": false,
    "task": "Active / Logged In",
    "email": "",
    "pronouns": "",
    "phonetic": "",
    "transit": "",
    "peers": "",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {},
    "formats": []
  },
  {
    "first_name": "Steven",
    "last_name": "Elejorde",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "esa474784@gnspes.ca",
    "pronouns": "He/him",
    "phonetic": "Ste-veen",
    "transit": "Sam Jason zephyr",
    "peers": "Sam Jason zephyr",
    "curious": "drug use or anything",
    "overdone": "Emotional regulation",
    "real_questions": "idk.",
    "teacher_note": "i play basketball for the Panthers.",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Deep",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Deep",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Deep",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Brief",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Deep",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Deep"
    },
    "formats": [
      "👥 Small-Group Problem Solving",
      "🧪 Hands-On Movement & Workshops"
    ]
  },
  {
    "first_name": "Zephyr",
    "last_name": "Gallagher",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "gzr464702@gnspes.ca",
    "pronouns": "he/him",
    "phonetic": "Z-ef-er",
    "transit": "Sam Mac and Steven",
    "peers": "Sam Mac and Steven",
    "curious": "Im excited about everything",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "Not really.",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Deep",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Brief",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Deep",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Brief",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Never",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Brief"
    },
    "formats": []
  },
  {
    "first_name": "Samuel",
    "last_name": "Hendricks Apud",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "hs986332@gnspes.ca",
    "pronouns": "he/him",
    "phonetic": "S-Am",
    "transit": "",
    "peers": "",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Deep",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Deep",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Deep",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Deep",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Deep",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Deep"
    },
    "formats": []
  },
  {
    "first_name": "Kenzie",
    "last_name": "King",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "kkm480567@gnspes.ca",
    "pronouns": "she/her",
    "phonetic": "",
    "transit": "Ainslie mercer, ruby cook, Juliet Miller",
    "peers": "Ainslie mercer, ruby cook, Juliet Miller",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Deep",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Over-Covered",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Never",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Over-Covered",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Deep",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Over-Covered"
    },
    "formats": []
  },
  {
    "first_name": "Jayden",
    "last_name": "Lee",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "ly602789@gnspes.ca",
    "pronouns": "him/he",
    "phonetic": "Jayden Lee",
    "transit": "mae",
    "peers": "mae",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Not Specified",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Not Specified",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Not Specified",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Not Specified",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Not Specified",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Not Specified"
    },
    "formats": []
  },
  {
    "first_name": "Jaela",
    "last_name": "Lorenz-Ashley",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "lajr483421@gnspes.ca",
    "pronouns": "she/they",
    "phonetic": "Jay-lah",
    "transit": "Sydney",
    "peers": "Sydney",
    "curious": "Learning cool things about mental health.",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Not Specified",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Not Specified",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Not Specified",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Not Specified",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Not Specified",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Not Specified"
    },
    "formats": []
  },
  {
    "first_name": "Trey",
    "last_name": "Lucas",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "lta504571@gnspes.ca",
    "pronouns": "he/him",
    "phonetic": "",
    "transit": "James",
    "peers": "James",
    "curious": "idk",
    "overdone": "AI",
    "real_questions": "managing stress",
    "teacher_note": "",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Over-Covered",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Over-Covered",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Deep",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Deep",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Deep",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Deep"
    },
    "formats": [
      "👥 Small-Group Problem Solving",
      "🎬 Video Breakdowns & Visual Media"
    ]
  },
  {
    "first_name": "Ruby",
    "last_name": "MacKay",
    "has_submitted": false,
    "task": "Active / Logged In",
    "email": "",
    "pronouns": "",
    "phonetic": "",
    "transit": "",
    "peers": "",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {},
    "formats": []
  },
  {
    "first_name": "Samuel",
    "last_name": "MacLellan",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "mst467507@gnspes.ca",
    "pronouns": "he/him",
    "phonetic": "",
    "transit": "Steven Zephyr and Nikolas",
    "peers": "Steven Zephyr and Nikolas",
    "curious": "I'm just looking forward to learning about new things",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Deep",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Brief",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Never",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Deep",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Deep",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Never"
    },
    "formats": []
  },
  {
    "first_name": "Marieke",
    "last_name": "Mans",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "mm474560@gnspes.ca",
    "pronouns": "she-her",
    "phonetic": "MA-REE-KA",
    "transit": "fiona, ruby m, ainslie, juliet",
    "peers": "fiona, ruby m, ainslie, juliet",
    "curious": "making friends",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Not Specified",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Not Specified",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Not Specified",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Not Specified",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Not Specified",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Not Specified"
    },
    "formats": []
  },
  {
    "first_name": "Ainslie",
    "last_name": "Mercer",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "maj476011@gnspes.ca",
    "pronouns": "She/Her",
    "phonetic": "Ains-LEE",
    "transit": "Juliet Miller, Mareike Mans, Fiona Schandall, Ruby Mackay.",
    "peers": "Juliet Miller, Mareike Mans, Fiona Schandall, Ruby Mackay.",
    "curious": "Dealing with group chat drama!!!!!",
    "overdone": "AI!! We di it almost all year in ILT and health and on fridays in ela we are tired of learning about chatbots.",
    "real_questions": "Dealing with group chat drama",
    "teacher_note": "",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Never",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Deep",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Brief",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Brief",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Brief",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Never"
    },
    "formats": [
      "🎯 Interactive Case Studies & Scenarios",
      "👥 Small-Group Problem Solving",
      "📥 Anonymous Question Box & Real Talk",
      "🎬 Video Breakdowns & Visual Media"
    ]
  },
  {
    "first_name": "Juliet",
    "last_name": "Miller",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "mjb488909@gnspes.ca",
    "pronouns": "she her",
    "phonetic": "JU-Lee-Et",
    "transit": "Ainslie, Kenzie, Fiona, Ruby M",
    "peers": "Ainslie, Kenzie, Fiona, Ruby M",
    "curious": "dealing with group chat drama",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Not Specified",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Not Specified",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Not Specified",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Not Specified",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Not Specified",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Not Specified"
    },
    "formats": []
  },
  {
    "first_name": "Samuel",
    "last_name": "Miller",
    "has_submitted": false,
    "task": "Active / Logged In",
    "email": "",
    "pronouns": "",
    "phonetic": "",
    "transit": "",
    "peers": "",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {},
    "formats": []
  },
  {
    "first_name": "Shaviah",
    "last_name": "O'Brien",
    "has_submitted": false,
    "task": "Active / Logged In",
    "email": "",
    "pronouns": "",
    "phonetic": "",
    "transit": "",
    "peers": "",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {},
    "formats": []
  },
  {
    "first_name": "Alex",
    "last_name": "Ramazanov",
    "has_submitted": false,
    "task": "Active / Logged In",
    "email": "",
    "pronouns": "",
    "phonetic": "",
    "transit": "",
    "peers": "",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {},
    "formats": []
  },
  {
    "first_name": "Samuel",
    "last_name": "Santos",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "sss770362@gnspes.ca",
    "pronouns": "He/him",
    "phonetic": "",
    "transit": "",
    "peers": "",
    "curious": "i am looking forward to learn about the importance of health and more",
    "overdone": "like the same old screen time on phone",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Over-Covered",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Deep",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Deep",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Over-Covered",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Brief",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Over-Covered"
    },
    "formats": []
  },
  {
    "first_name": "Sydney",
    "last_name": "Sawyer-Patterson",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "spsjm474222@gnspes.ca",
    "pronouns": "she/her",
    "phonetic": "Sydney Sawyer-Patterson",
    "transit": "",
    "peers": "",
    "curious": "health things like body learning about last year  we didn't get into drugs and etc",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Not Specified",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Not Specified",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Not Specified",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Not Specified",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Not Specified",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Not Specified"
    },
    "formats": []
  },
  {
    "first_name": "Fiona",
    "last_name": "Schandall",
    "has_submitted": false,
    "task": "Active / Logged In",
    "email": "",
    "pronouns": "",
    "phonetic": "",
    "transit": "",
    "peers": "",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {},
    "formats": []
  },
  {
    "first_name": "Nehemiah",
    "last_name": "Skeete",
    "has_submitted": false,
    "task": "Active / Logged In",
    "email": "",
    "pronouns": "",
    "phonetic": "",
    "transit": "",
    "peers": "",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {},
    "formats": []
  },
  {
    "first_name": "Nikolas",
    "last_name": "Stulac",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "sna464744@gnspes.ca",
    "pronouns": "he/him",
    "phonetic": "",
    "transit": "James, Sam Mac, Nai",
    "peers": "James, Sam Mac, Nai",
    "curious": "learning new things",
    "overdone": "alcohol use and vaping",
    "real_questions": "I'm not sure",
    "teacher_note": "",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Deep",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Over-Covered",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Deep",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Brief",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Brief",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Over-Covered"
    },
    "formats": [
      "👥 Small-Group Problem Solving",
      "🎬 Video Breakdowns & Visual Media"
    ]
  },
  {
    "first_name": "James",
    "last_name": "Taiani",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "tjp461492@gnspes.ca",
    "pronouns": "he",
    "phonetic": "none",
    "transit": "nik trey nai",
    "peers": "nik trey nai",
    "curious": "sports and sleep",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Not Specified",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Not Specified",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Not Specified",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Not Specified",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Not Specified",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Not Specified"
    },
    "formats": []
  },
  {
    "first_name": "Julia",
    "last_name": "Tylak",
    "has_submitted": false,
    "task": "Active / Logged In",
    "email": "",
    "pronouns": "",
    "phonetic": "",
    "transit": "",
    "peers": "",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {},
    "formats": []
  },
  {
    "first_name": "Martin",
    "last_name": "Vanslyke",
    "has_submitted": false,
    "task": "Active / Logged In",
    "email": "",
    "pronouns": "",
    "phonetic": "",
    "transit": "",
    "peers": "",
    "curious": "",
    "overdone": "",
    "real_questions": "",
    "teacher_note": "",
    "matrix": {},
    "formats": []
  },
  {
    "first_name": "Alex",
    "last_name": "Warby",
    "has_submitted": true,
    "task": "Healthy Living 8: Grade 7 Learning Audit",
    "email": "wa718206@gnspes.ca",
    "pronouns": "she/her",
    "phonetic": "my name sounds like alixz warbie but its spelt Alex warby",
    "transit": "Fiona, ainslie, Kenzie, julia.",
    "peers": "Fiona, ainslie, Kenzie, julia.",
    "curious": "learning true things",
    "overdone": "ai chat gbt",
    "real_questions": "I don't know",
    "teacher_note": "I want to sit with my friends",
    "matrix": {
      "Decision-Making, Peer Norms & Emotional Coping (HL7 Outcome 1)": "Brief",
      "Tech Habits, Sleep Quality, Nutrition & Disease Prevention (HL7 Outcome 2)": "Deep",
      "Mental Health Literacy, Brain Mechanics & Resiliency (HL7 Outcome 3)": "Never",
      "Puberty, Body Image Pressures & Sexual/Reproductive Health (HL7 Outcome 4)": "Over-Covered",
      "Relationships, Boundaries, Digital Laws & Exploitation Awareness (HL7 Outcome 5)": "Over-Covered",
      "Substance Literacy, Harms, Refusal & Brain Growth (HL7 Outcome 6)": "Brief"
    },
    "formats": []
  }
];
