// hl9_sleep_feedback.js - GENERATED by tools/marks_md.py --sync
// Source of truth: HealthyLiving9/Unit 1 - Sleep/HL9_SleepClinic_901_Marks.md
// Edit the .md, re-run the sync. This file feeds the 'Teacher feedback'
// field on HL9_Class1_10_Station_Audit_Template.html.
// Band: 4 Stellar | 3 Satisfactory | 2 Needs work

window.HL9_SLEEP_FEEDBACK = {
 "ABE": {
  "band": 4,
  "bandName": "Stellar",
  "comment": "The figures are close but not clean (83% against the key). Weekly debt is (9 − hours) × 5, so recompute any row that drifted. The case reading is the good part — Lily's 5:45 bus, Grace's rumination, Amara's family obligation came through correctly, which is exactly what the clinic was testing. Recheck 04 Jenna against the key.",
  "name": "Abby"
 },
 "ARE": {
  "band": 4,
  "bandName": "Stellar",
  "comment": "Good telemetry — figures and risk levels land on the key 87% of the time. The case reading is the good part — Lily's 5:45 bus, Amara's family obligation came through correctly, which is exactly what the clinic was testing.",
  "name": "Adie"
 },
 "AVP": {
  "band": 3,
  "bandName": "Satisfactory",
  "comment": "The figures are close but not clean (78% against the key). Weekly debt is (9 − hours) × 5, so recompute any row that drifted. The case reading is the good part — Priya (the healthy control), Lily's 5:45 bus, Amara's family obligation came through correctly, which is exactly what the clinic was testing. Watch 08 Grace (phone) — that walks into the trap the file is built around. Recheck 09 Owen against the key. Also look at the 09/10 rows — Amara's figures appear on Owen's line.",
  "name": "Avery"
 },
 "BEG": {
  "band": 3,
  "bandName": "Satisfactory",
  "comment": "The figures are close but not clean (75% against the key). Weekly debt is (9 − hours) × 5, so recompute any row that drifted. The case reading is the good part — Lily's 5:45 bus, Grace's rumination, Amara's family obligation came through correctly, which is exactly what the clinic was testing. Watch 03 Marcus (phone) — that walks into the trap the file is built around. Recheck 05 Isaiah against the key.",
  "name": "Benjamin"
 },
 "BRE": {
  "band": 4,
  "bandName": "Stellar",
  "comment": "The figures are close but not clean (83% against the key). Weekly debt is (9 − hours) × 5, so recompute any row that drifted. The case reading is the good part — Lily's 5:45 bus, Grace's rumination, Amara's family obligation came through correctly, which is exactly what the clinic was testing. Recheck 04 Jenna against the key.",
  "name": "Brielle"
 },
 "CAB": {
  "band": 4,
  "bandName": "Stellar",
  "comment": "Good telemetry — figures and risk levels land on the key 97% of the time. The case reading is the good part — Grace's rumination, Amara's family obligation came through correctly, which is exactly what the clinic was testing. Watch 02 Priya (need) — that walks into the trap the file is built around.",
  "name": "Clara"
 },
 "DUK": {
  "band": 3,
  "bandName": "Satisfactory",
  "comment": "The figures are close but not clean (78% against the key). Weekly debt is (9 − hours) × 5, so recompute any row that drifted. The case reading is the good part — Lily's 5:45 bus, Grace's rumination, Amara's family obligation came through correctly, which is exactly what the clinic was testing. Watch 03 Marcus (phone) — that walks into the trap the file is built around. Recheck 05 Isaiah against the key.",
  "name": "Doun"
 },
 "MAT": {
  "band": 4,
  "bandName": "Stellar",
  "comment": "Good telemetry — figures and risk levels land on the key 98% of the time. The case reading is the good part — Grace's rumination, Amara's family obligation came through correctly, which is exactly what the clinic was testing. Watch 02 Priya (need) — that walks into the trap the file is built around.",
  "name": "Madeleine"
 },
 "MPU": {
  "band": 3,
  "bandName": "Satisfactory",
  "comment": "The figures are close but not clean (77% against the key). Weekly debt is (9 − hours) × 5, so recompute any row that drifted. The case reading is the good part — Lily's 5:45 bus, Grace's rumination came through correctly, which is exactly what the clinic was testing. Recheck 04 Jenna and 09 Owen against the key. Also look at the 09/10 rows — Amara's figures appear on Owen's line.",
  "name": "Marty"
 },
 "NAC": {
  "band": 3,
  "bandName": "Satisfactory",
  "comment": "The maths is the weak spot (57% against the key). Weekly debt is (9 − hours) × 5 school nights — that formula is most of what went wrong. The case reading is the good part — Priya (the healthy control), Amara's family obligation came through correctly, which is exactly what the clinic was testing. Recheck 03 Marcus and 05 Isaiah against the key. Also look at the 09/10 rows — Amara's figures appear on Owen's line.",
  "name": "Nolan"
 },
 "NNG": {
  "band": 2,
  "bandName": "Needs work",
  "comment": "The maths is the weak spot (50% against the key). Weekly debt is (9 − hours) × 5 school nights — that formula is most of what went wrong. The case reading is the good part — Lily's 5:45 bus, Grace's rumination, Amara's family obligation came through correctly, which is exactly what the clinic was testing. Recheck 01 Devon and 03 Marcus against the key. Also look at the 09/10 rows — Amara's figures appear on Owen's line.",
  "name": "Finn"
 },
 "SAN": {
  "band": 3,
  "bandName": "Satisfactory",
  "comment": "The figures are close but not clean (75% against the key). Weekly debt is (9 − hours) × 5, so recompute any row that drifted. The case reading is the good part — Priya (the healthy control), Lily's 5:45 bus, Grace's rumination, Amara's family obligation came through correctly, which is exactly what the clinic was testing. Recheck 09 Owen and 10 Amara against the key. Also look at the 09/10 rows — Amara's figures appear on Owen's line.",
  "name": "Isaac"
 },
 "TRH": {
  "band": 2,
  "bandName": "Needs work",
  "comment": "The maths is the weak spot (45% against the key). Weekly debt is (9 − hours) × 5 school nights — that formula is most of what went wrong. The case reading is the good part — Lily's 5:45 bus came through correctly, which is exactly what the clinic was testing. Recheck 01 Devon and 03 Marcus against the key. Also look at the 09/10 rows — Amara's figures appear on Owen's line.",
  "name": "Trenton"
 }
};
