// Auto-generated Brainstorm Data from Google Sheets
window.PLACES_BRAINSTORM_DATA = {
  "kossy": {
    "timestamp": "9/3/2026 13:33:03",
    "raw_name": "kossy",
    "matched_name": "kossy",
    "pin": "",
    "class": "903",
    "cat1_personal": "my house and my bed , my house because it cozy in there and my bed is beacuse i love laying down ad just taking either a nap or just doing nothing or going on my phone",
    "cat2_community": "mic mall, halifax shopping centre(becaus ei hang out w my friend )",
    "cat3_global": "",
    "cat4_aspirational": "florida or the UK i wanna go to the UK because my ccousin and his parents are there and i miss them, while florida because i think its really cool over there from what i see on tiktok.",
    "cat5_music": "i don't have one",
    "youtube_url": ""
  },
  "BEE": {
    "timestamp": "9/3/2026 13:46:23",
    "raw_name": "Bella Kustudic Burke",
    "matched_name": "Bella Foley",
    "pin": "BEE",
    "class": "802",
    "cat1_personal": "my house because it holds all my memories.and my school because it holdfs all my memories.",
    "cat2_community": "my school because i have lots of my memories from school.and the mall because i go there a lot.",
    "cat3_global": "Roam because my family is from there.Europ because my family is from there.",
    "cat4_aspirational": "cuba because its hot. iceland because its cold.",
    "cat5_music": "the song little sally walker takes me back to grade 3 with my best friend.",
    "youtube_url": ""
  },
  "bellakustudicburke": {
    "timestamp": "9/3/2026 13:46:23",
    "raw_name": "Bella Kustudic Burke",
    "matched_name": "Bella Foley",
    "pin": "BEE",
    "class": "802",
    "cat1_personal": "my house because it holds all my memories.and my school because it holdfs all my memories.",
    "cat2_community": "my school because i have lots of my memories from school.and the mall because i go there a lot.",
    "cat3_global": "Roam because my family is from there.Europ because my family is from there.",
    "cat4_aspirational": "cuba because its hot. iceland because its cold.",
    "cat5_music": "the song little sally walker takes me back to grade 3 with my best friend.",
    "youtube_url": ""
  },
  "bellafoley": {
    "timestamp": "9/3/2026 13:46:23",
    "raw_name": "Bella Kustudic Burke",
    "matched_name": "Bella Foley",
    "pin": "BEE",
    "class": "802",
    "cat1_personal": "my house because it holds all my memories.and my school because it holdfs all my memories.",
    "cat2_community": "my school because i have lots of my memories from school.and the mall because i go there a lot.",
    "cat3_global": "Roam because my family is from there.Europ because my family is from there.",
    "cat4_aspirational": "cuba because its hot. iceland because its cold.",
    "cat5_music": "the song little sally walker takes me back to grade 3 with my best friend.",
    "youtube_url": ""
  },
  "KEK": {
    "timestamp": "9/3/2026 13:42:03",
    "raw_name": "kenzie",
    "matched_name": "Kenzie King",
    "pin": "KEK",
    "class": "801",
    "cat1_personal": "my childhood home. we used to live there i rememember us having family partys and we had a really fancy old car in the garage.\n2, school because i always get to see my friends and we always laugh our gyatts off and all the teachers love us .",
    "cat2_community": "my friend zoe house. i rememember i used to barge into her house at like 730 am and we always hang out there and play roblox.\nthe sportslex. me and all my friends hang out there and we also work out and make a full of ourselfs",
    "cat3_global": "",
    "cat4_aspirational": "i dream of going to nyc during the winter. because it looks so pretty and getting a apartment with a huge view. \nhawaii. another dream place i would love to go too and just always be swimming and do school out there. and they have good schools out there so i would love it and id get a beach house and have a small cat",
    "cat5_music": "okay the song thinking of you by katy perry is a senstive topic for me because i would listen to it everyday with my mom and then 7th grade it founds it way back to me. i remember being in my old house and listening to it while my mom cooks dinner and then id go and watch barbie",
    "youtube_url": ""
  },
  "kenzie": {
    "timestamp": "9/3/2026 13:42:03",
    "raw_name": "kenzie",
    "matched_name": "Kenzie King",
    "pin": "KEK",
    "class": "801",
    "cat1_personal": "my childhood home. we used to live there i rememember us having family partys and we had a really fancy old car in the garage.\n2, school because i always get to see my friends and we always laugh our gyatts off and all the teachers love us .",
    "cat2_community": "my friend zoe house. i rememember i used to barge into her house at like 730 am and we always hang out there and play roblox.\nthe sportslex. me and all my friends hang out there and we also work out and make a full of ourselfs",
    "cat3_global": "",
    "cat4_aspirational": "i dream of going to nyc during the winter. because it looks so pretty and getting a apartment with a huge view. \nhawaii. another dream place i would love to go too and just always be swimming and do school out there. and they have good schools out there so i would love it and id get a beach house and have a small cat",
    "cat5_music": "okay the song thinking of you by katy perry is a senstive topic for me because i would listen to it everyday with my mom and then 7th grade it founds it way back to me. i remember being in my old house and listening to it while my mom cooks dinner and then id go and watch barbie",
    "youtube_url": ""
  },
  "kenzieking": {
    "timestamp": "9/3/2026 13:42:03",
    "raw_name": "kenzie",
    "matched_name": "Kenzie King",
    "pin": "KEK",
    "class": "801",
    "cat1_personal": "my childhood home. we used to live there i rememember us having family partys and we had a really fancy old car in the garage.\n2, school because i always get to see my friends and we always laugh our gyatts off and all the teachers love us .",
    "cat2_community": "my friend zoe house. i rememember i used to barge into her house at like 730 am and we always hang out there and play roblox.\nthe sportslex. me and all my friends hang out there and we also work out and make a full of ourselfs",
    "cat3_global": "",
    "cat4_aspirational": "i dream of going to nyc during the winter. because it looks so pretty and getting a apartment with a huge view. \nhawaii. another dream place i would love to go too and just always be swimming and do school out there. and they have good schools out there so i would love it and id get a beach house and have a small cat",
    "cat5_music": "okay the song thinking of you by katy perry is a senstive topic for me because i would listen to it everyday with my mom and then 7th grade it founds it way back to me. i remember being in my old house and listening to it while my mom cooks dinner and then id go and watch barbie",
    "youtube_url": ""
  },
  "MAR": {
    "timestamp": "9/3/2026 13:47:54",
    "raw_name": "Maia",
    "matched_name": "Maia Rendell",
    "pin": "MAR",
    "class": "903",
    "cat1_personal": "Gwenna's house, Gwenna's home feels very special to me. I feel welcome when I walk in and reno greets me. I also enjoy me and Ollies foot fives.",
    "cat2_community": "Fundy scoops,I really like going to Fundy scoops. Me and Gwenna have many memories there and made multiple friends.",
    "cat3_global": "",
    "cat4_aspirational": "Europe. I want to go to Europe so bad. It has so many cool places to visit and tourist spots.",
    "cat5_music": "Bonnie Tyler - Holding Out For A Hero (Official HD Video)\n\nYouTube \u00b7 Bonnie Tyler\n320.3M+ views \u00b7 10 years ago\nhttps://www.youtube.com/watch?v=6JCLY0Rlx6Q\n\nThese songs link back to many memories !",
    "youtube_url": "https://www.youtube.com/watch?v=6JCLY0Rlx6Q"
  },
  "maia": {
    "timestamp": "9/3/2026 13:47:54",
    "raw_name": "Maia",
    "matched_name": "Maia Rendell",
    "pin": "MAR",
    "class": "903",
    "cat1_personal": "Gwenna's house, Gwenna's home feels very special to me. I feel welcome when I walk in and reno greets me. I also enjoy me and Ollies foot fives.",
    "cat2_community": "Fundy scoops,I really like going to Fundy scoops. Me and Gwenna have many memories there and made multiple friends.",
    "cat3_global": "",
    "cat4_aspirational": "Europe. I want to go to Europe so bad. It has so many cool places to visit and tourist spots.",
    "cat5_music": "Bonnie Tyler - Holding Out For A Hero (Official HD Video)\n\nYouTube \u00b7 Bonnie Tyler\n320.3M+ views \u00b7 10 years ago\nhttps://www.youtube.com/watch?v=6JCLY0Rlx6Q\n\nThese songs link back to many memories !",
    "youtube_url": "https://www.youtube.com/watch?v=6JCLY0Rlx6Q"
  },
  "maiarendell": {
    "timestamp": "9/3/2026 13:47:54",
    "raw_name": "Maia",
    "matched_name": "Maia Rendell",
    "pin": "MAR",
    "class": "903",
    "cat1_personal": "Gwenna's house, Gwenna's home feels very special to me. I feel welcome when I walk in and reno greets me. I also enjoy me and Ollies foot fives.",
    "cat2_community": "Fundy scoops,I really like going to Fundy scoops. Me and Gwenna have many memories there and made multiple friends.",
    "cat3_global": "",
    "cat4_aspirational": "Europe. I want to go to Europe so bad. It has so many cool places to visit and tourist spots.",
    "cat5_music": "Bonnie Tyler - Holding Out For A Hero (Official HD Video)\n\nYouTube \u00b7 Bonnie Tyler\n320.3M+ views \u00b7 10 years ago\nhttps://www.youtube.com/watch?v=6JCLY0Rlx6Q\n\nThese songs link back to many memories !",
    "youtube_url": "https://www.youtube.com/watch?v=6JCLY0Rlx6Q"
  },
  "GWW": {
    "timestamp": "9/3/2026 13:50:40",
    "raw_name": "gwenna",
    "matched_name": "Gwenna White",
    "pin": "GWW",
    "class": "903",
    "cat1_personal": "maias house, winnie is super cute and ms.rendell is very wolcoming to me and her loft is super cute.",
    "cat2_community": "halifax shopping center,i love to shop and my favorite hobbie is shopping and the best part about this mall is that it hasd a aritzia.aritzia is my happy place and i love it.",
    "cat3_global": "irerland, my moms mom is from ierland but she was just born there shes dosent actualy have any irish in her.me  my mom and my brother went there and visites my grandmothers house.",
    "cat4_aspirational": "italy i just think it would be a wonderfull trip i wanna go super bad.",
    "cat5_music": "eye of the tiger by katy perry in pre primary we always listend to it",
    "youtube_url": ""
  },
  "gwenna": {
    "timestamp": "9/3/2026 13:50:40",
    "raw_name": "gwenna",
    "matched_name": "Gwenna White",
    "pin": "GWW",
    "class": "903",
    "cat1_personal": "maias house, winnie is super cute and ms.rendell is very wolcoming to me and her loft is super cute.",
    "cat2_community": "halifax shopping center,i love to shop and my favorite hobbie is shopping and the best part about this mall is that it hasd a aritzia.aritzia is my happy place and i love it.",
    "cat3_global": "irerland, my moms mom is from ierland but she was just born there shes dosent actualy have any irish in her.me  my mom and my brother went there and visites my grandmothers house.",
    "cat4_aspirational": "italy i just think it would be a wonderfull trip i wanna go super bad.",
    "cat5_music": "eye of the tiger by katy perry in pre primary we always listend to it",
    "youtube_url": ""
  },
  "gwennawhite": {
    "timestamp": "9/3/2026 13:50:40",
    "raw_name": "gwenna",
    "matched_name": "Gwenna White",
    "pin": "GWW",
    "class": "903",
    "cat1_personal": "maias house, winnie is super cute and ms.rendell is very wolcoming to me and her loft is super cute.",
    "cat2_community": "halifax shopping center,i love to shop and my favorite hobbie is shopping and the best part about this mall is that it hasd a aritzia.aritzia is my happy place and i love it.",
    "cat3_global": "irerland, my moms mom is from ierland but she was just born there shes dosent actualy have any irish in her.me  my mom and my brother went there and visites my grandmothers house.",
    "cat4_aspirational": "italy i just think it would be a wonderfull trip i wanna go super bad.",
    "cat5_music": "eye of the tiger by katy perry in pre primary we always listend to it",
    "youtube_url": ""
  },
  "ZEM": {
    "timestamp": "9/3/2026 13:52:19",
    "raw_name": "Zoe",
    "matched_name": "Zoe Muise",
    "pin": "ZEM",
    "class": "903",
    "cat1_personal": "My house because ive lived there my whole life and so many of my memorys have been made in that house. My parents have lived there for around 20 years and theyve helped me make so many memorys there aswell. \n\nBicentennial school because ive been here for 10 years now and ive met all my friends here. Over the years ive had many great teachers and ive made many great friends while being here.",
    "cat2_community": "The mall because I hang out there with friends all the time and I really enjoy shopping there aswell.\n\nBeasley feild because thats where my track team trains in the summer and fall. Ive trained there for so many years and I love being there.",
    "cat3_global": "England. My mom is from there and every two years me, my mom, and sometimes my dad go over there to viset family and see the sights.\n\nYarmouth Nova Scotia because thats where my dad is from and we always go see my grandma at christmas.",
    "cat4_aspirational": "Hawaii, Ive really wanted to go to Hawaii for so long because it seems so warm and fun to travel to.\n\nLos Angeles. I really want to go there because thats where Billie eilish is and it would be really fun to see her in concert. The weather also seems really nice and the beaches look super nice.",
    "cat5_music": "https://www.youtube.com/watch?v=ru0K8uYEZWw&themeRefresh=1\nThe song Cant stop the feeling by Justin Timberlake because it used to be my favorire song and in grade 1 and my music teacher used to play it all the time.",
    "youtube_url": "https://www.youtube.com/watch?v=ru0K8uYEZWw"
  },
  "zoe": {
    "timestamp": "9/3/2026 13:52:19",
    "raw_name": "Zoe",
    "matched_name": "Zoe Muise",
    "pin": "ZEM",
    "class": "903",
    "cat1_personal": "My house because ive lived there my whole life and so many of my memorys have been made in that house. My parents have lived there for around 20 years and theyve helped me make so many memorys there aswell. \n\nBicentennial school because ive been here for 10 years now and ive met all my friends here. Over the years ive had many great teachers and ive made many great friends while being here.",
    "cat2_community": "The mall because I hang out there with friends all the time and I really enjoy shopping there aswell.\n\nBeasley feild because thats where my track team trains in the summer and fall. Ive trained there for so many years and I love being there.",
    "cat3_global": "England. My mom is from there and every two years me, my mom, and sometimes my dad go over there to viset family and see the sights.\n\nYarmouth Nova Scotia because thats where my dad is from and we always go see my grandma at christmas.",
    "cat4_aspirational": "Hawaii, Ive really wanted to go to Hawaii for so long because it seems so warm and fun to travel to.\n\nLos Angeles. I really want to go there because thats where Billie eilish is and it would be really fun to see her in concert. The weather also seems really nice and the beaches look super nice.",
    "cat5_music": "https://www.youtube.com/watch?v=ru0K8uYEZWw&themeRefresh=1\nThe song Cant stop the feeling by Justin Timberlake because it used to be my favorire song and in grade 1 and my music teacher used to play it all the time.",
    "youtube_url": "https://www.youtube.com/watch?v=ru0K8uYEZWw"
  },
  "zoemuise": {
    "timestamp": "9/3/2026 13:52:19",
    "raw_name": "Zoe",
    "matched_name": "Zoe Muise",
    "pin": "ZEM",
    "class": "903",
    "cat1_personal": "My house because ive lived there my whole life and so many of my memorys have been made in that house. My parents have lived there for around 20 years and theyve helped me make so many memorys there aswell. \n\nBicentennial school because ive been here for 10 years now and ive met all my friends here. Over the years ive had many great teachers and ive made many great friends while being here.",
    "cat2_community": "The mall because I hang out there with friends all the time and I really enjoy shopping there aswell.\n\nBeasley feild because thats where my track team trains in the summer and fall. Ive trained there for so many years and I love being there.",
    "cat3_global": "England. My mom is from there and every two years me, my mom, and sometimes my dad go over there to viset family and see the sights.\n\nYarmouth Nova Scotia because thats where my dad is from and we always go see my grandma at christmas.",
    "cat4_aspirational": "Hawaii, Ive really wanted to go to Hawaii for so long because it seems so warm and fun to travel to.\n\nLos Angeles. I really want to go there because thats where Billie eilish is and it would be really fun to see her in concert. The weather also seems really nice and the beaches look super nice.",
    "cat5_music": "https://www.youtube.com/watch?v=ru0K8uYEZWw&themeRefresh=1\nThe song Cant stop the feeling by Justin Timberlake because it used to be my favorire song and in grade 1 and my music teacher used to play it all the time.",
    "youtube_url": "https://www.youtube.com/watch?v=ru0K8uYEZWw"
  },
  "olisalcedo": {
    "timestamp": "9/3/2026 13:53:12",
    "raw_name": "Oli Salcedo",
    "matched_name": "Oli Salcedo",
    "pin": "",
    "class": "903",
    "cat1_personal": "Cowbay when my parents first got divorced my dad moved there and it was a nice change.\nEast Coast Varcity Ive played soccer there almost my whole life and i love soccer",
    "cat2_community": "Mic Mac mall because I go there so much and I know a lot of the workers and every one is super nice. Sullivans pond I love how the geese can just do what ever they want and no one cares.",
    "cat3_global": "Well my dad was born in venezuela and he makes my family venezuelan food like adepas sometimes. My mom and my dad met in Jamacia and my dad has a lot of storys from his visit.",
    "cat4_aspirational": "I would love to go to Tokyo Japan because I love the culture there and the veiws are pretty nice. I would like to visit alberta because over summer i went to a sleep away camp for about 20 days and a lot of my friends from it live there and i miss them a lot",
    "cat5_music": "The first technoligy me and my brother ever had was a super tiny music player and my favourite song was guns N'Roses \"Live And Let Die\"\n\nhttps://www.youtube.com/watch?v=iXKVA5Xs90M&list=RDiXKVA5Xs90M&start_radio=1",
    "youtube_url": "https://www.youtube.com/watch?v=iXKVA5Xs90M"
  },
  "CMA": {
    "timestamp": "9/3/2026 13:53:39",
    "raw_name": "Callum MacDonald",
    "matched_name": "Callum MacDonald",
    "pin": "CMA",
    "class": "903",
    "cat1_personal": "wolfvillie because me and my old basketball team played a torment there and it was fun.\n my house because i have lots of good memory's there",
    "cat2_community": "the wave in Halifax because it was fun to climb.\nfindly center because i played basketball with my friends there a lot.",
    "cat3_global": "Cape Breton because all my family lives there.\nToronto because some of my cousins live there.",
    "cat4_aspirational": "Europe because it looks cool.\nand England because i wanna see the big Ben",
    "cat5_music": "https://www.youtube.com/watch?v=SlCXgj2bS_A \nthis song because i use to listen to it at my cottage",
    "youtube_url": "https://www.youtube.com/watch?v=SlCXgj2bS_A"
  },
  "callummacdonald": {
    "timestamp": "9/3/2026 13:53:39",
    "raw_name": "Callum MacDonald",
    "matched_name": "Callum MacDonald",
    "pin": "CMA",
    "class": "903",
    "cat1_personal": "wolfvillie because me and my old basketball team played a torment there and it was fun.\n my house because i have lots of good memory's there",
    "cat2_community": "the wave in Halifax because it was fun to climb.\nfindly center because i played basketball with my friends there a lot.",
    "cat3_global": "Cape Breton because all my family lives there.\nToronto because some of my cousins live there.",
    "cat4_aspirational": "Europe because it looks cool.\nand England because i wanna see the big Ben",
    "cat5_music": "https://www.youtube.com/watch?v=SlCXgj2bS_A \nthis song because i use to listen to it at my cottage",
    "youtube_url": "https://www.youtube.com/watch?v=SlCXgj2bS_A"
  },
  "PSA": {
    "timestamp": "9/3/2026 13:56:01",
    "raw_name": "Patience",
    "matched_name": "Patience Sampson",
    "pin": "PSA",
    "class": "903",
    "cat1_personal": "My first landmark would be Highfield Park, because that's where my Nan, Mom, and all me and my siblings grew up.\n\nMy bed has lots of memories including me sleeping and sleepovers and family friends chilling on it.",
    "cat2_community": "My Nan likes to take me and my sibling to the Cole Harbour Pool, so thats my first choice.\n\nMy second choice would have to be school because I've made a good amount of my friends here.",
    "cat3_global": "One side of my family is from Cape Breton and they are purely Caucasian and we go down once every 2 years to spend time with cousins and they have a really cute dog named Hunter.\n\nThe other side of my family lives in Virginia, Norfolk, and Washington. DC so the trips down there are pretty fun because Nova Scotia can get pretty boring.",
    "cat4_aspirational": "I want to go to Philippines because of the weather (not in spring) and I like their foods.\n\nI also wanna go to Germany because of the Neuschwanstein Castle, which I did a project on in tech ed last year!",
    "cat5_music": "Hotel California is a good song for me to chose because my Nan introduced it to me when I was pretty young, and everytime I hear it I think of her.\n\nEagles - Hotel California (Official Audio)\nYouTube \u00b7 Eagles\nMar 25, 2025",
    "youtube_url": ""
  },
  "patience": {
    "timestamp": "9/3/2026 13:56:01",
    "raw_name": "Patience",
    "matched_name": "Patience Sampson",
    "pin": "PSA",
    "class": "903",
    "cat1_personal": "My first landmark would be Highfield Park, because that's where my Nan, Mom, and all me and my siblings grew up.\n\nMy bed has lots of memories including me sleeping and sleepovers and family friends chilling on it.",
    "cat2_community": "My Nan likes to take me and my sibling to the Cole Harbour Pool, so thats my first choice.\n\nMy second choice would have to be school because I've made a good amount of my friends here.",
    "cat3_global": "One side of my family is from Cape Breton and they are purely Caucasian and we go down once every 2 years to spend time with cousins and they have a really cute dog named Hunter.\n\nThe other side of my family lives in Virginia, Norfolk, and Washington. DC so the trips down there are pretty fun because Nova Scotia can get pretty boring.",
    "cat4_aspirational": "I want to go to Philippines because of the weather (not in spring) and I like their foods.\n\nI also wanna go to Germany because of the Neuschwanstein Castle, which I did a project on in tech ed last year!",
    "cat5_music": "Hotel California is a good song for me to chose because my Nan introduced it to me when I was pretty young, and everytime I hear it I think of her.\n\nEagles - Hotel California (Official Audio)\nYouTube \u00b7 Eagles\nMar 25, 2025",
    "youtube_url": ""
  },
  "patiencesampson": {
    "timestamp": "9/3/2026 13:56:01",
    "raw_name": "Patience",
    "matched_name": "Patience Sampson",
    "pin": "PSA",
    "class": "903",
    "cat1_personal": "My first landmark would be Highfield Park, because that's where my Nan, Mom, and all me and my siblings grew up.\n\nMy bed has lots of memories including me sleeping and sleepovers and family friends chilling on it.",
    "cat2_community": "My Nan likes to take me and my sibling to the Cole Harbour Pool, so thats my first choice.\n\nMy second choice would have to be school because I've made a good amount of my friends here.",
    "cat3_global": "One side of my family is from Cape Breton and they are purely Caucasian and we go down once every 2 years to spend time with cousins and they have a really cute dog named Hunter.\n\nThe other side of my family lives in Virginia, Norfolk, and Washington. DC so the trips down there are pretty fun because Nova Scotia can get pretty boring.",
    "cat4_aspirational": "I want to go to Philippines because of the weather (not in spring) and I like their foods.\n\nI also wanna go to Germany because of the Neuschwanstein Castle, which I did a project on in tech ed last year!",
    "cat5_music": "Hotel California is a good song for me to chose because my Nan introduced it to me when I was pretty young, and everytime I hear it I think of her.\n\nEagles - Hotel California (Official Audio)\nYouTube \u00b7 Eagles\nMar 25, 2025",
    "youtube_url": ""
  },
  "AAM": {
    "timestamp": "9/3/2026 13:56:05",
    "raw_name": "Liam MacLean",
    "matched_name": "Liam MacLean",
    "pin": "AAM",
    "class": "903",
    "cat1_personal": "A place that hold a special meaning to me is my home because it is where I have lived my entire life and where I keep all of my belongings. Another place that holds a special meaning to me is my paddling club Senobe. This place is special to me because it is where I have been paddling for many years and where ive made lots of friends.",
    "cat2_community": "Crichton Park school is important to me because it was the elementary school I went to and where I made most of my friends that I have today. Banook lake is significant to me because it is the lake I have paddled and trained on for most of my life.",
    "cat3_global": "Nova scotia because it is where me and my parents were born.",
    "cat4_aspirational": "I want to go to Niagra fall some day because it looks super cool and I have never seen any big waterfalls in person. I would like to go to Canadas wonderland because I want to go on the huge rollercoasters.",
    "cat5_music": "https://www.youtube.com/watch?v=GcYVCvBq0FY",
    "youtube_url": "https://www.youtube.com/watch?v=GcYVCvBq0FY"
  },
  "liammaclean": {
    "timestamp": "9/3/2026 13:56:05",
    "raw_name": "Liam MacLean",
    "matched_name": "Liam MacLean",
    "pin": "AAM",
    "class": "903",
    "cat1_personal": "A place that hold a special meaning to me is my home because it is where I have lived my entire life and where I keep all of my belongings. Another place that holds a special meaning to me is my paddling club Senobe. This place is special to me because it is where I have been paddling for many years and where ive made lots of friends.",
    "cat2_community": "Crichton Park school is important to me because it was the elementary school I went to and where I made most of my friends that I have today. Banook lake is significant to me because it is the lake I have paddled and trained on for most of my life.",
    "cat3_global": "Nova scotia because it is where me and my parents were born.",
    "cat4_aspirational": "I want to go to Niagra fall some day because it looks super cool and I have never seen any big waterfalls in person. I would like to go to Canadas wonderland because I want to go on the huge rollercoasters.",
    "cat5_music": "https://www.youtube.com/watch?v=GcYVCvBq0FY",
    "youtube_url": "https://www.youtube.com/watch?v=GcYVCvBq0FY"
  },
  "MSK": {
    "timestamp": "9/3/2026 13:56:54",
    "raw_name": "Misha Coronel",
    "matched_name": "Misha Kaplin",
    "pin": "MSK",
    "class": "802",
    "cat1_personal": "Two locations that hold a special meaning to me are Toronto and the Philippines. The Philippines is where I grew up which is my hometown. I made a lot of memories there and it really feels like home. Toronto was where I used to live and made a lot of connections. I went there this summer and met with my friends.",
    "cat2_community": "My house and my aunt's house are two places I like at most. I like my home since I can just be comfortable. I like being at home because I don't like being outside. I also like my aunt's house since it's the same as my home. I like being there because my family spends a lot of quality time.",
    "cat3_global": "Kuwait was where I used to live for a while when I was younger. I liked it there because it was really peaceful. I'd say it's the same for Nova Scotia, I like it here because it's also pretty chill.",
    "cat4_aspirational": "I really want to live in South Korea one day. I like their culture and I wanna study there. I also want to visit Japan since my cousins live there. I also want to experience how they live there.",
    "cat5_music": "https://youtu.be/xy3AcmW0lrQ?si=2Z7KXWaZfiMagzPG",
    "youtube_url": "https://youtu.be/xy3AcmW0lrQ"
  },
  "mishacoronel": {
    "timestamp": "9/3/2026 13:56:54",
    "raw_name": "Misha Coronel",
    "matched_name": "Misha Kaplin",
    "pin": "MSK",
    "class": "802",
    "cat1_personal": "Two locations that hold a special meaning to me are Toronto and the Philippines. The Philippines is where I grew up which is my hometown. I made a lot of memories there and it really feels like home. Toronto was where I used to live and made a lot of connections. I went there this summer and met with my friends.",
    "cat2_community": "My house and my aunt's house are two places I like at most. I like my home since I can just be comfortable. I like being at home because I don't like being outside. I also like my aunt's house since it's the same as my home. I like being there because my family spends a lot of quality time.",
    "cat3_global": "Kuwait was where I used to live for a while when I was younger. I liked it there because it was really peaceful. I'd say it's the same for Nova Scotia, I like it here because it's also pretty chill.",
    "cat4_aspirational": "I really want to live in South Korea one day. I like their culture and I wanna study there. I also want to visit Japan since my cousins live there. I also want to experience how they live there.",
    "cat5_music": "https://youtu.be/xy3AcmW0lrQ?si=2Z7KXWaZfiMagzPG",
    "youtube_url": "https://youtu.be/xy3AcmW0lrQ"
  },
  "mishakaplin": {
    "timestamp": "9/3/2026 13:56:54",
    "raw_name": "Misha Coronel",
    "matched_name": "Misha Kaplin",
    "pin": "MSK",
    "class": "802",
    "cat1_personal": "Two locations that hold a special meaning to me are Toronto and the Philippines. The Philippines is where I grew up which is my hometown. I made a lot of memories there and it really feels like home. Toronto was where I used to live and made a lot of connections. I went there this summer and met with my friends.",
    "cat2_community": "My house and my aunt's house are two places I like at most. I like my home since I can just be comfortable. I like being at home because I don't like being outside. I also like my aunt's house since it's the same as my home. I like being there because my family spends a lot of quality time.",
    "cat3_global": "Kuwait was where I used to live for a while when I was younger. I liked it there because it was really peaceful. I'd say it's the same for Nova Scotia, I like it here because it's also pretty chill.",
    "cat4_aspirational": "I really want to live in South Korea one day. I like their culture and I wanna study there. I also want to visit Japan since my cousins live there. I also want to experience how they live there.",
    "cat5_music": "https://youtu.be/xy3AcmW0lrQ?si=2Z7KXWaZfiMagzPG",
    "youtube_url": "https://youtu.be/xy3AcmW0lrQ"
  },
  "AVP": {
    "timestamp": "9/3/2026 13:57:16",
    "raw_name": "Avery Fisher",
    "matched_name": "Avery Peters",
    "pin": "AVP",
    "class": "901",
    "cat1_personal": "My old house, it's where my parents and I lived for a long time with my cat. London because my parents liver there for two years and I recently saw it for the first time.",
    "cat2_community": "The Dartmouth common because I grew up playing golf and base ball there. This school because I've gone here since I was born.",
    "cat3_global": "My cottage because my great grandfather built it along time ago and multiple generations have went there. The Scandinavian Countries because my family are from there.",
    "cat4_aspirational": "Findland in 2 years because the World Junoirs are hosted there. Germany because I love learning about WW2.",
    "cat5_music": "https://www.youtube.com/watch?v=IFu5Dr6drF8 and https://www.youtube.com/watch?v=uXLOa83-fUA . Both of these songs are played every year at my cottage.",
    "youtube_url": "https://www.youtube.com/watch?v=IFu5Dr6drF8"
  },
  "averyfisher": {
    "timestamp": "9/3/2026 13:57:16",
    "raw_name": "Avery Fisher",
    "matched_name": "Avery Peters",
    "pin": "AVP",
    "class": "901",
    "cat1_personal": "My old house, it's where my parents and I lived for a long time with my cat. London because my parents liver there for two years and I recently saw it for the first time.",
    "cat2_community": "The Dartmouth common because I grew up playing golf and base ball there. This school because I've gone here since I was born.",
    "cat3_global": "My cottage because my great grandfather built it along time ago and multiple generations have went there. The Scandinavian Countries because my family are from there.",
    "cat4_aspirational": "Findland in 2 years because the World Junoirs are hosted there. Germany because I love learning about WW2.",
    "cat5_music": "https://www.youtube.com/watch?v=IFu5Dr6drF8 and https://www.youtube.com/watch?v=uXLOa83-fUA . Both of these songs are played every year at my cottage.",
    "youtube_url": "https://www.youtube.com/watch?v=IFu5Dr6drF8"
  },
  "averypeters": {
    "timestamp": "9/3/2026 13:57:16",
    "raw_name": "Avery Fisher",
    "matched_name": "Avery Peters",
    "pin": "AVP",
    "class": "901",
    "cat1_personal": "My old house, it's where my parents and I lived for a long time with my cat. London because my parents liver there for two years and I recently saw it for the first time.",
    "cat2_community": "The Dartmouth common because I grew up playing golf and base ball there. This school because I've gone here since I was born.",
    "cat3_global": "My cottage because my great grandfather built it along time ago and multiple generations have went there. The Scandinavian Countries because my family are from there.",
    "cat4_aspirational": "Findland in 2 years because the World Junoirs are hosted there. Germany because I love learning about WW2.",
    "cat5_music": "https://www.youtube.com/watch?v=IFu5Dr6drF8 and https://www.youtube.com/watch?v=uXLOa83-fUA . Both of these songs are played every year at my cottage.",
    "youtube_url": "https://www.youtube.com/watch?v=IFu5Dr6drF8"
  },
  "SHA": {
    "timestamp": "9/3/2026 13:58:46",
    "raw_name": "Zeiden Sampang",
    "matched_name": "Sam Harrison",
    "pin": "SHA",
    "class": "802",
    "cat1_personal": "My first location would be my first apartment that I had moved away from in February of 2020.\nI lived there for eight years and had made so many memories with my parents and brothers. Me and my brothers would always play games together on a Wii in the living room and it had made so many good memories.\n\nMy second location would be my cousin's house.\nI've had a lot of family parties there and also spent time with a lot of my family during the holidays.",
    "cat2_community": "Bicentennial School is my choice for a local community location.\nI chose Bicentennial School because of how many friends I made, meeting great teachers, and learning a lot of cool things.\n\nMy second community location is",
    "cat3_global": "The Philippines is one of my global locations.\nI've only gone there a few times to visit family but every time I go there I spend a lot of time with that family doing a lot of fun things. Just last year I went bowling, swimming, I took a lot of walks and a lot more. Being there is so fun whenever I get the chance.",
    "cat4_aspirational": "I'd like to go to LA because of how nice it looks and its weather. It also looks very fun to be there with how much freedom and activity you can do.",
    "cat5_music": "Whenever I play les by Childish Gambino I think of my old house because of how much it was played there by my brothers.",
    "youtube_url": ""
  },
  "paulinecsamillano": {
    "timestamp": "9/3/2026 13:58:41",
    "raw_name": "Pauline C. Samillano",
    "matched_name": "Sam Harrison",
    "pin": "SHA",
    "class": "802",
    "cat1_personal": "My house, holds so many memories that will always be tied to me no matter what. Though there were times when something shouldn't be kept in my mind, I personally think that's what makes a home, a home. Not to mention the good times I've had with others in my home. \n\nSchool, It may not be something I always look forward to, but the memories that I make here, is something I could never relive. All of the times when I was with my friends, teachers, and just being here, makes me realize that this is a one time thing, and I should take every moment for granted.",
    "cat2_community": "The Commons, just being with my family, and friends there, always makes such good memories. And I enjoy every second and minute when I'm there. \n\nThe Mic Mac Mall, always going there will unlock memories I've kept in the back of my mind and have forgotten about it. Makes me feel really nostalgic when I go through each area of the place.",
    "cat3_global": "Saudi Arabia, I was born here, which would make sense with all of the older memories I've made with others. Whenever I get reminded of the place I would never forget, it always makes me feel really nice. \n\nThe Philippines, though I've never been there for long, even when I'm from there. I remember all the people I've met that I haven't seen in so long nowadays, always makes miss them a lot! Especially the place I was living at that time.",
    "cat4_aspirational": "South Korea, all of the food I've seen from there, makes my stomach grumble every time, and the place just looks gorgeous from the pictures I've seen before.\n\nGermany, I've dreamed about going there, as I don't have much information about the place. I've always wanted to learn the language as it really interest me.",
    "cat5_music": "High Hopes by Panic! At the disco, always hearing it on social media, or even on the radio always makes me think about the older memories I've created, and not to mention, it was my favorite song of all time before I started to grow older and older.",
    "youtube_url": ""
  },
  "samharrison": {
    "timestamp": "9/3/2026 13:58:46",
    "raw_name": "Zeiden Sampang",
    "matched_name": "Sam Harrison",
    "pin": "SHA",
    "class": "802",
    "cat1_personal": "My first location would be my first apartment that I had moved away from in February of 2020.\nI lived there for eight years and had made so many memories with my parents and brothers. Me and my brothers would always play games together on a Wii in the living room and it had made so many good memories.\n\nMy second location would be my cousin's house.\nI've had a lot of family parties there and also spent time with a lot of my family during the holidays.",
    "cat2_community": "Bicentennial School is my choice for a local community location.\nI chose Bicentennial School because of how many friends I made, meeting great teachers, and learning a lot of cool things.\n\nMy second community location is",
    "cat3_global": "The Philippines is one of my global locations.\nI've only gone there a few times to visit family but every time I go there I spend a lot of time with that family doing a lot of fun things. Just last year I went bowling, swimming, I took a lot of walks and a lot more. Being there is so fun whenever I get the chance.",
    "cat4_aspirational": "I'd like to go to LA because of how nice it looks and its weather. It also looks very fun to be there with how much freedom and activity you can do.",
    "cat5_music": "Whenever I play les by Childish Gambino I think of my old house because of how much it was played there by my brothers.",
    "youtube_url": ""
  },
  "zeidensampang": {
    "timestamp": "9/3/2026 13:58:46",
    "raw_name": "Zeiden Sampang",
    "matched_name": "Sam Harrison",
    "pin": "SHA",
    "class": "802",
    "cat1_personal": "My first location would be my first apartment that I had moved away from in February of 2020.\nI lived there for eight years and had made so many memories with my parents and brothers. Me and my brothers would always play games together on a Wii in the living room and it had made so many good memories.\n\nMy second location would be my cousin's house.\nI've had a lot of family parties there and also spent time with a lot of my family during the holidays.",
    "cat2_community": "Bicentennial School is my choice for a local community location.\nI chose Bicentennial School because of how many friends I made, meeting great teachers, and learning a lot of cool things.\n\nMy second community location is",
    "cat3_global": "The Philippines is one of my global locations.\nI've only gone there a few times to visit family but every time I go there I spend a lot of time with that family doing a lot of fun things. Just last year I went bowling, swimming, I took a lot of walks and a lot more. Being there is so fun whenever I get the chance.",
    "cat4_aspirational": "I'd like to go to LA because of how nice it looks and its weather. It also looks very fun to be there with how much freedom and activity you can do.",
    "cat5_music": "Whenever I play les by Childish Gambino I think of my old house because of how much it was played there by my brothers.",
    "youtube_url": ""
  },
  "SCP": {
    "timestamp": "9/3/2026 13:59:21",
    "raw_name": "Oscar Donaldson",
    "matched_name": "Oscar Pinks",
    "pin": "SCP",
    "class": "902",
    "cat1_personal": "There was a mermorial back sometime before July that was held for my great grandfather in England, reconizing the roll that he played in WW2. Im not actually sure if he has a monument dedacated to him, but I dont have any other ideas.\n\nSecond is my house, because I dont have any ideas left, nothing that is significant",
    "cat2_community": "I think one is this school, because I've gone here for 10 years, no other schoool, and I've had a great time (almost) every year\n\nand maybe Cole Harbour, because my uncle played AAA hocket there growing up, and I'm from Dartmouth so I respect them as hokcey adversaries",
    "cat3_global": "I think Kent, England is a significant place because my granparents live there\n\nAnd also London, England because my dad is from there",
    "cat4_aspirational": "I think I would like to visit Tampa Bay to see a Tampa Bay Lightning game (Once Trump isn't president)\n\nMaybe Portugal, because a lot of my family also wants to see it, and i've never been",
    "cat5_music": "We were once down on my great uncles warf, by the see, and where fishing for crabs, and my dad cept playing \"Crabs In The Bucket\"\n\nI dont know who its by, sorry",
    "youtube_url": ""
  },
  "oscardonaldson": {
    "timestamp": "9/3/2026 13:59:21",
    "raw_name": "Oscar Donaldson",
    "matched_name": "Oscar Pinks",
    "pin": "SCP",
    "class": "902",
    "cat1_personal": "There was a mermorial back sometime before July that was held for my great grandfather in England, reconizing the roll that he played in WW2. Im not actually sure if he has a monument dedacated to him, but I dont have any other ideas.\n\nSecond is my house, because I dont have any ideas left, nothing that is significant",
    "cat2_community": "I think one is this school, because I've gone here for 10 years, no other schoool, and I've had a great time (almost) every year\n\nand maybe Cole Harbour, because my uncle played AAA hocket there growing up, and I'm from Dartmouth so I respect them as hokcey adversaries",
    "cat3_global": "I think Kent, England is a significant place because my granparents live there\n\nAnd also London, England because my dad is from there",
    "cat4_aspirational": "I think I would like to visit Tampa Bay to see a Tampa Bay Lightning game (Once Trump isn't president)\n\nMaybe Portugal, because a lot of my family also wants to see it, and i've never been",
    "cat5_music": "We were once down on my great uncles warf, by the see, and where fishing for crabs, and my dad cept playing \"Crabs In The Bucket\"\n\nI dont know who its by, sorry",
    "youtube_url": ""
  },
  "oscarpinks": {
    "timestamp": "9/3/2026 13:59:21",
    "raw_name": "Oscar Donaldson",
    "matched_name": "Oscar Pinks",
    "pin": "SCP",
    "class": "902",
    "cat1_personal": "There was a mermorial back sometime before July that was held for my great grandfather in England, reconizing the roll that he played in WW2. Im not actually sure if he has a monument dedacated to him, but I dont have any other ideas.\n\nSecond is my house, because I dont have any ideas left, nothing that is significant",
    "cat2_community": "I think one is this school, because I've gone here for 10 years, no other schoool, and I've had a great time (almost) every year\n\nand maybe Cole Harbour, because my uncle played AAA hocket there growing up, and I'm from Dartmouth so I respect them as hokcey adversaries",
    "cat3_global": "I think Kent, England is a significant place because my granparents live there\n\nAnd also London, England because my dad is from there",
    "cat4_aspirational": "I think I would like to visit Tampa Bay to see a Tampa Bay Lightning game (Once Trump isn't president)\n\nMaybe Portugal, because a lot of my family also wants to see it, and i've never been",
    "cat5_music": "We were once down on my great uncles warf, by the see, and where fishing for crabs, and my dad cept playing \"Crabs In The Bucket\"\n\nI dont know who its by, sorry",
    "youtube_url": ""
  },
  "TMM": {
    "timestamp": "9/3/2026 13:59:54",
    "raw_name": "Tommy",
    "matched_name": "Tommy MacInnes",
    "pin": "TMM",
    "class": "903",
    "cat1_personal": "Wolfville. Me and my family go up to wolfville every year to go apple picking.",
    "cat2_community": "A place in my local community that is significant to me would be peggys cove. Me and my family love going to peggys cove and climbing the rocks. Rainbow haven beach. I love rainbow haven because i like swimming in the ocean and i hangout with freinds there.",
    "cat3_global": "Scotland and Ireland. My mom side is from Ireland, she moved here when she was 13. And my dads side is from Scotland but he has lived in canada since he was 3.",
    "cat4_aspirational": "I would love to go to Switzerland because it looks beautiful there on the moutains. I would also love to go to Italy. I would like to go to Italy because of all the good food.",
    "cat5_music": "I dont have a specific song but my dads favorite musican was bruce springsteen and I remember his music since I was very young.",
    "youtube_url": ""
  },
  "tommy": {
    "timestamp": "9/3/2026 13:59:54",
    "raw_name": "Tommy",
    "matched_name": "Tommy MacInnes",
    "pin": "TMM",
    "class": "903",
    "cat1_personal": "Wolfville. Me and my family go up to wolfville every year to go apple picking.",
    "cat2_community": "A place in my local community that is significant to me would be peggys cove. Me and my family love going to peggys cove and climbing the rocks. Rainbow haven beach. I love rainbow haven because i like swimming in the ocean and i hangout with freinds there.",
    "cat3_global": "Scotland and Ireland. My mom side is from Ireland, she moved here when she was 13. And my dads side is from Scotland but he has lived in canada since he was 3.",
    "cat4_aspirational": "I would love to go to Switzerland because it looks beautiful there on the moutains. I would also love to go to Italy. I would like to go to Italy because of all the good food.",
    "cat5_music": "I dont have a specific song but my dads favorite musican was bruce springsteen and I remember his music since I was very young.",
    "youtube_url": ""
  },
  "tommymacinnes": {
    "timestamp": "9/3/2026 13:59:54",
    "raw_name": "Tommy",
    "matched_name": "Tommy MacInnes",
    "pin": "TMM",
    "class": "903",
    "cat1_personal": "Wolfville. Me and my family go up to wolfville every year to go apple picking.",
    "cat2_community": "A place in my local community that is significant to me would be peggys cove. Me and my family love going to peggys cove and climbing the rocks. Rainbow haven beach. I love rainbow haven because i like swimming in the ocean and i hangout with freinds there.",
    "cat3_global": "Scotland and Ireland. My mom side is from Ireland, she moved here when she was 13. And my dads side is from Scotland but he has lived in canada since he was 3.",
    "cat4_aspirational": "I would love to go to Switzerland because it looks beautiful there on the moutains. I would also love to go to Italy. I would like to go to Italy because of all the good food.",
    "cat5_music": "I dont have a specific song but my dads favorite musican was bruce springsteen and I remember his music since I was very young.",
    "youtube_url": ""
  },
  "APA": {
    "timestamp": "9/3/2026 14:01:18",
    "raw_name": "April Flaherty",
    "matched_name": "April Flaherty",
    "pin": "APA",
    "class": "903",
    "cat1_personal": "The Pointe du chien warf is a special sopt to me because every year I go there with my family. I have been going to the Pointe du chien warf since I was a baby. \n\nBanook Canoe Club is another special spot for me because when I was younger I went and paddled ther every summer.",
    "cat2_community": "Basinview Drive Community School in Bedford, I go there all the time for dance compotitions.\n\nCrichton Park elementry school was my elementry school. I spent a lot of time there.",
    "cat3_global": "Sharbot Lake in Ontario has been in my family for so many years. I go there every summer and I have been going there since I was born.\n\nIerland, my familys haritage comes from Ierland.",
    "cat4_aspirational": "I want to go to Flahertys irish pub in Ierland, I am a Flaherty. I think it would be really cool to go there. \n\nI want to go to Scotland and do the world championship for highland dance.",
    "cat5_music": "https://www.youtube.com/watch?v=c6rP-YP4c5I\n\nMy grade 1 teacher would play this song every day at the end of the day.",
    "youtube_url": "https://www.youtube.com/watch?v=c6rP-YP4c5I"
  },
  "aprilflaherty": {
    "timestamp": "9/3/2026 14:01:18",
    "raw_name": "April Flaherty",
    "matched_name": "April Flaherty",
    "pin": "APA",
    "class": "903",
    "cat1_personal": "The Pointe du chien warf is a special sopt to me because every year I go there with my family. I have been going to the Pointe du chien warf since I was a baby. \n\nBanook Canoe Club is another special spot for me because when I was younger I went and paddled ther every summer.",
    "cat2_community": "Basinview Drive Community School in Bedford, I go there all the time for dance compotitions.\n\nCrichton Park elementry school was my elementry school. I spent a lot of time there.",
    "cat3_global": "Sharbot Lake in Ontario has been in my family for so many years. I go there every summer and I have been going there since I was born.\n\nIerland, my familys haritage comes from Ierland.",
    "cat4_aspirational": "I want to go to Flahertys irish pub in Ierland, I am a Flaherty. I think it would be really cool to go there. \n\nI want to go to Scotland and do the world championship for highland dance.",
    "cat5_music": "https://www.youtube.com/watch?v=c6rP-YP4c5I\n\nMy grade 1 teacher would play this song every day at the end of the day.",
    "youtube_url": "https://www.youtube.com/watch?v=c6rP-YP4c5I"
  },
  "AVG": {
    "timestamp": "9/3/2026 14:02:26",
    "raw_name": "Ava Giacomantonio",
    "matched_name": "Ava Giacomantonio",
    "pin": "AVG",
    "class": "903",
    "cat1_personal": "Cottage: My moms family has owned a cottage in Pictou for 55 years. It doesn't hold one specific memory, but I can remember going there for around a month of every summer since I could remember and it's a happy place.\n118 Highway: During covid my dad and stepmom realised we were finishing our school work quickly so they decided to make their own classes to keep us busy. I have a very vivid memory of my dad making me and my siblings act like we were military marching down the 118 for phys ed.",
    "cat2_community": "Shubie Park: This is my favorite place to take a brain break and walk my dogs.\nLake Banook. Kayaking is my favorite sport. I do year round training with some of my best friends and make my best memories at Banook.",
    "cat3_global": "Italy: My entire dads side is Italian. Every christmas we go to my great uncles houses that they decorate in ALOT of lights and eat a bunch of homeade Italian food.\nThe lobster in Shediac: We take photos at the big lobster in Shediac anually. We hang many of the photos in our house.",
    "cat4_aspirational": "Seoul: I love the korean culture, food and people so I have books and dictionaries all based around South Korea. I really love ramen...\nLucky Bay: I really want to go to this beach in Australia because I heard it was the most beautiful. It seems simmilar to Bondi beach, but less people.",
    "cat5_music": "https://www.youtube.com/watch?v=sYfmQ5eAQlg",
    "youtube_url": "https://www.youtube.com/watch?v=sYfmQ5eAQlg"
  },
  "avagiacomantonio": {
    "timestamp": "9/3/2026 14:02:26",
    "raw_name": "Ava Giacomantonio",
    "matched_name": "Ava Giacomantonio",
    "pin": "AVG",
    "class": "903",
    "cat1_personal": "Cottage: My moms family has owned a cottage in Pictou for 55 years. It doesn't hold one specific memory, but I can remember going there for around a month of every summer since I could remember and it's a happy place.\n118 Highway: During covid my dad and stepmom realised we were finishing our school work quickly so they decided to make their own classes to keep us busy. I have a very vivid memory of my dad making me and my siblings act like we were military marching down the 118 for phys ed.",
    "cat2_community": "Shubie Park: This is my favorite place to take a brain break and walk my dogs.\nLake Banook. Kayaking is my favorite sport. I do year round training with some of my best friends and make my best memories at Banook.",
    "cat3_global": "Italy: My entire dads side is Italian. Every christmas we go to my great uncles houses that they decorate in ALOT of lights and eat a bunch of homeade Italian food.\nThe lobster in Shediac: We take photos at the big lobster in Shediac anually. We hang many of the photos in our house.",
    "cat4_aspirational": "Seoul: I love the korean culture, food and people so I have books and dictionaries all based around South Korea. I really love ramen...\nLucky Bay: I really want to go to this beach in Australia because I heard it was the most beautiful. It seems simmilar to Bondi beach, but less people.",
    "cat5_music": "https://www.youtube.com/watch?v=sYfmQ5eAQlg",
    "youtube_url": "https://www.youtube.com/watch?v=sYfmQ5eAQlg"
  },
  "EVS": {
    "timestamp": "9/3/2026 14:03:14",
    "raw_name": "Evan Smith",
    "matched_name": "Evan Smith",
    "pin": "EVS",
    "class": "903",
    "cat1_personal": "1. My home. I've been living there for 6 years, and I have made countless memories while living here.\n2. Bihi. There have been ups and downs, but what is life without highs and lows?",
    "cat2_community": "1. Mic Mac Mall. I go there every once in a while and always have a great time.\n2. The Bridge Terminal. It's very convenient for me to get around the city, and I like it because of that.",
    "cat3_global": "1. Scotland, I think? I'm pretty sure some of my family came from there, but I'm not sure.\n2. Ireland. Similar to Scotland, I don't really know where my family's background is from. It's been a while.",
    "cat4_aspirational": "1. Singapore Changi Airport. If you see the photos of it, it genuinely looks like the 8th Wonder Of The World. \n2. Toronto. I've had enough time to truly experience it, only stops at Pearson and 2-day trips.",
    "cat5_music": "Unfortunately, I don't really have a song that really connects to my life before third grade. I wasn't a big music guy when I was younger, so I don't have an authentic answer to this that wouldn't feel like lying.",
    "youtube_url": ""
  },
  "evansmith": {
    "timestamp": "9/3/2026 14:03:14",
    "raw_name": "Evan Smith",
    "matched_name": "Evan Smith",
    "pin": "EVS",
    "class": "903",
    "cat1_personal": "1. My home. I've been living there for 6 years, and I have made countless memories while living here.\n2. Bihi. There have been ups and downs, but what is life without highs and lows?",
    "cat2_community": "1. Mic Mac Mall. I go there every once in a while and always have a great time.\n2. The Bridge Terminal. It's very convenient for me to get around the city, and I like it because of that.",
    "cat3_global": "1. Scotland, I think? I'm pretty sure some of my family came from there, but I'm not sure.\n2. Ireland. Similar to Scotland, I don't really know where my family's background is from. It's been a while.",
    "cat4_aspirational": "1. Singapore Changi Airport. If you see the photos of it, it genuinely looks like the 8th Wonder Of The World. \n2. Toronto. I've had enough time to truly experience it, only stops at Pearson and 2-day trips.",
    "cat5_music": "Unfortunately, I don't really have a song that really connects to my life before third grade. I wasn't a big music guy when I was younger, so I don't have an authentic answer to this that wouldn't feel like lying.",
    "youtube_url": ""
  },
  "BEV": {
    "timestamp": "9/3/2026 14:03:20",
    "raw_name": "Ben Fost",
    "matched_name": "Ben Veach",
    "pin": "BEV",
    "class": "803",
    "cat1_personal": "The Wave, and My house. The wave I have many good memories of climbing, even though they say don't climb it. And my house holds memories of me learning guitar, funny memories, and good memories.",
    "cat2_community": "Sportsplex, and Camp Kidston. Sportsplex is the place I go to improve and better myself, it makes me feel happy because of that. And Camp Kidston, don't even get me started, that place is my second home, most of the friend I have made have come from that place, its always welcoming and loving towards anybody who comes, I have only good memories from that place, and only good friends.",
    "cat3_global": "Newfoundland, And England. Newfoundland is where my father was born, we visited it a couple of years ago so that me and my sister could learn about how my father grew up. Same applies to my mother and her roots in england.",
    "cat4_aspirational": "Paris, and Portugal. Paris is pretty obvious, its the best tourist attraction in the world with the Eiffel Tower. And Portugal is because of the food, the places, and the beauty of it.",
    "cat5_music": "https://www.youtube.com/watch?v=L_jWHffIx5E Smash Mouth- All Star",
    "youtube_url": "https://www.youtube.com/watch?v=L_jWHffIx5E"
  },
  "benfost": {
    "timestamp": "9/3/2026 14:03:20",
    "raw_name": "Ben Fost",
    "matched_name": "Ben Veach",
    "pin": "BEV",
    "class": "803",
    "cat1_personal": "The Wave, and My house. The wave I have many good memories of climbing, even though they say don't climb it. And my house holds memories of me learning guitar, funny memories, and good memories.",
    "cat2_community": "Sportsplex, and Camp Kidston. Sportsplex is the place I go to improve and better myself, it makes me feel happy because of that. And Camp Kidston, don't even get me started, that place is my second home, most of the friend I have made have come from that place, its always welcoming and loving towards anybody who comes, I have only good memories from that place, and only good friends.",
    "cat3_global": "Newfoundland, And England. Newfoundland is where my father was born, we visited it a couple of years ago so that me and my sister could learn about how my father grew up. Same applies to my mother and her roots in england.",
    "cat4_aspirational": "Paris, and Portugal. Paris is pretty obvious, its the best tourist attraction in the world with the Eiffel Tower. And Portugal is because of the food, the places, and the beauty of it.",
    "cat5_music": "https://www.youtube.com/watch?v=L_jWHffIx5E Smash Mouth- All Star",
    "youtube_url": "https://www.youtube.com/watch?v=L_jWHffIx5E"
  },
  "benveach": {
    "timestamp": "9/3/2026 14:03:20",
    "raw_name": "Ben Fost",
    "matched_name": "Ben Veach",
    "pin": "BEV",
    "class": "803",
    "cat1_personal": "The Wave, and My house. The wave I have many good memories of climbing, even though they say don't climb it. And my house holds memories of me learning guitar, funny memories, and good memories.",
    "cat2_community": "Sportsplex, and Camp Kidston. Sportsplex is the place I go to improve and better myself, it makes me feel happy because of that. And Camp Kidston, don't even get me started, that place is my second home, most of the friend I have made have come from that place, its always welcoming and loving towards anybody who comes, I have only good memories from that place, and only good friends.",
    "cat3_global": "Newfoundland, And England. Newfoundland is where my father was born, we visited it a couple of years ago so that me and my sister could learn about how my father grew up. Same applies to my mother and her roots in england.",
    "cat4_aspirational": "Paris, and Portugal. Paris is pretty obvious, its the best tourist attraction in the world with the Eiffel Tower. And Portugal is because of the food, the places, and the beauty of it.",
    "cat5_music": "https://www.youtube.com/watch?v=L_jWHffIx5E Smash Mouth- All Star",
    "youtube_url": "https://www.youtube.com/watch?v=L_jWHffIx5E"
  },
  "ADC": {
    "timestamp": "9/3/2026 14:04:38",
    "raw_name": "Addy Crawford",
    "matched_name": "Addy Crawford",
    "pin": "ADC",
    "class": "903",
    "cat1_personal": "My old house is special to me because I grew up there and have so many good and bad memories there.\n\nMy elementary school music teachers room. His room is a core memory because he introduced me to great music and made me fine my love in music. I have always visted him to talk about music.",
    "cat2_community": "Forest road: Forest Road is the street I grew up on. It has a special meaning to me because when I was younger I knew everyone and was very social with the neigbours which gave me some of the most memories.\n\n The old Sportsplex: Sportsplex holds a memory of when I was younger and would constantly be there with my dad.",
    "cat3_global": "Ireland is apart of my dad's culture because, it's where my dad's father is from and most family on that side.\n\nCape breaton is where most of my moms side of the family is and we are lucky to visit often.",
    "cat4_aspirational": "Somewhere in Nothern Italy I really want to go there because one of my favorite movies was filmed there and I'd love to visit\n\nI really want to go to England with my grandparents because they've gone every year and Ive always wanted to go with them to see all kinds of cool stores.",
    "cat5_music": "I'll belive in anything by Wolf Parade is my favourite song and is rooted in me. This song means so much to me and reminds me of how lucky I am to have supportive family and friends.",
    "youtube_url": ""
  },
  "addycrawford": {
    "timestamp": "9/3/2026 14:04:38",
    "raw_name": "Addy Crawford",
    "matched_name": "Addy Crawford",
    "pin": "ADC",
    "class": "903",
    "cat1_personal": "My old house is special to me because I grew up there and have so many good and bad memories there.\n\nMy elementary school music teachers room. His room is a core memory because he introduced me to great music and made me fine my love in music. I have always visted him to talk about music.",
    "cat2_community": "Forest road: Forest Road is the street I grew up on. It has a special meaning to me because when I was younger I knew everyone and was very social with the neigbours which gave me some of the most memories.\n\n The old Sportsplex: Sportsplex holds a memory of when I was younger and would constantly be there with my dad.",
    "cat3_global": "Ireland is apart of my dad's culture because, it's where my dad's father is from and most family on that side.\n\nCape breaton is where most of my moms side of the family is and we are lucky to visit often.",
    "cat4_aspirational": "Somewhere in Nothern Italy I really want to go there because one of my favorite movies was filmed there and I'd love to visit\n\nI really want to go to England with my grandparents because they've gone every year and Ive always wanted to go with them to see all kinds of cool stores.",
    "cat5_music": "I'll belive in anything by Wolf Parade is my favourite song and is rooted in me. This song means so much to me and reminds me of how lucky I am to have supportive family and friends.",
    "youtube_url": ""
  },
  "ZAS": {
    "timestamp": "9/3/2026 14:06:05",
    "raw_name": "Zana Shala",
    "matched_name": "Zana Shala",
    "pin": "ZAS",
    "class": "903",
    "cat1_personal": "My grandmothers, house in Kosovo. The reason why, is because I remember going there with  all of my cousins when we were kids, and it was just a very special and important time that I still think about.",
    "cat2_community": "The mall. I have meet so many  new people ther and have made so many memories.\nAddys house. Me andaddy have made so many memories there, and i spend so much time there it feels like my second home.",
    "cat3_global": "Pristina, Kosovo. The reasoning behind why i chose Pristina is because this is where me and my entire family is from. Its a very special place to me and I visit it everysingle summer.\nMy aunts house. I still find my aunts house very special to my persanal family because when we first moved to Canada we spent majority of our time there learing, and meeting new peaole. We still go there very often for holidays, birthdays, or  special days.",
    "cat4_aspirational": "the Lombardy region of Northern Italy. I really want to go there because my favoirite movie, Call  me by your name was filmed there, and it just looks like such a beatiful place.\nI also really want to go to new york, because so many movies that I really enjoy were filmed there, and it just looks llike such a magical  place, but i mostly want to  go there during the winter.",
    "cat5_music": "The song that reminds me of a special moment is the song Freak. Everytime i listen to it, it reminds me of when i was in grade 5, and i listened to it almost every single day.\nhttps://www.youtube.com/watch?v=NfMegACVJQw",
    "youtube_url": "https://www.youtube.com/watch?v=NfMegACVJQw"
  },
  "zanashala": {
    "timestamp": "9/3/2026 14:06:05",
    "raw_name": "Zana Shala",
    "matched_name": "Zana Shala",
    "pin": "ZAS",
    "class": "903",
    "cat1_personal": "My grandmothers, house in Kosovo. The reason why, is because I remember going there with  all of my cousins when we were kids, and it was just a very special and important time that I still think about.",
    "cat2_community": "The mall. I have meet so many  new people ther and have made so many memories.\nAddys house. Me andaddy have made so many memories there, and i spend so much time there it feels like my second home.",
    "cat3_global": "Pristina, Kosovo. The reasoning behind why i chose Pristina is because this is where me and my entire family is from. Its a very special place to me and I visit it everysingle summer.\nMy aunts house. I still find my aunts house very special to my persanal family because when we first moved to Canada we spent majority of our time there learing, and meeting new peaole. We still go there very often for holidays, birthdays, or  special days.",
    "cat4_aspirational": "the Lombardy region of Northern Italy. I really want to go there because my favoirite movie, Call  me by your name was filmed there, and it just looks like such a beatiful place.\nI also really want to go to new york, because so many movies that I really enjoy were filmed there, and it just looks llike such a magical  place, but i mostly want to  go there during the winter.",
    "cat5_music": "The song that reminds me of a special moment is the song Freak. Everytime i listen to it, it reminds me of when i was in grade 5, and i listened to it almost every single day.\nhttps://www.youtube.com/watch?v=NfMegACVJQw",
    "youtube_url": "https://www.youtube.com/watch?v=NfMegACVJQw"
  }
};
window.PLACES_BRAINSTORM_LIST = [
  {
    "timestamp": "9/3/2026 13:33:03",
    "raw_name": "kossy",
    "matched_name": "kossy",
    "pin": "",
    "class": "903",
    "cat1_personal": "my house and my bed , my house because it cozy in there and my bed is beacuse i love laying down ad just taking either a nap or just doing nothing or going on my phone",
    "cat2_community": "mic mall, halifax shopping centre(becaus ei hang out w my friend )",
    "cat3_global": "",
    "cat4_aspirational": "florida or the UK i wanna go to the UK because my ccousin and his parents are there and i miss them, while florida because i think its really cool over there from what i see on tiktok.",
    "cat5_music": "i don't have one",
    "youtube_url": ""
  },
  {
    "timestamp": "9/3/2026 13:38:00",
    "raw_name": "Bella Kustudic Burke",
    "matched_name": "Bella Foley",
    "pin": "BEE",
    "class": "802",
    "cat1_personal": "My house because i lived there my whole life and have lots of memories there.my school because i have lots of memories.",
    "cat2_community": "my school because it has lots of memories.",
    "cat3_global": "nova scotia because I live here.",
    "cat4_aspirational": "i want to go to cuba because it sounds cool and the food from there looks good. also ist hot there and i want to go someware hot.",
    "cat5_music": "the song little sally walker brings me back to grade 3 when me and my bestfriend loved that song.",
    "youtube_url": ""
  },
  {
    "timestamp": "9/3/2026 13:42:03",
    "raw_name": "kenzie",
    "matched_name": "Kenzie King",
    "pin": "KEK",
    "class": "801",
    "cat1_personal": "my childhood home. we used to live there i rememember us having family partys and we had a really fancy old car in the garage.\n2, school because i always get to see my friends and we always laugh our gyatts off and all the teachers love us .",
    "cat2_community": "my friend zoe house. i rememember i used to barge into her house at like 730 am and we always hang out there and play roblox.\nthe sportslex. me and all my friends hang out there and we also work out and make a full of ourselfs",
    "cat3_global": "",
    "cat4_aspirational": "i dream of going to nyc during the winter. because it looks so pretty and getting a apartment with a huge view. \nhawaii. another dream place i would love to go too and just always be swimming and do school out there. and they have good schools out there so i would love it and id get a beach house and have a small cat",
    "cat5_music": "okay the song thinking of you by katy perry is a senstive topic for me because i would listen to it everyday with my mom and then 7th grade it founds it way back to me. i remember being in my old house and listening to it while my mom cooks dinner and then id go and watch barbie",
    "youtube_url": ""
  },
  {
    "timestamp": "9/3/2026 13:46:23",
    "raw_name": "Bella Kustudic Burke",
    "matched_name": "Bella Foley",
    "pin": "BEE",
    "class": "802",
    "cat1_personal": "my house because it holds all my memories.and my school because it holdfs all my memories.",
    "cat2_community": "my school because i have lots of my memories from school.and the mall because i go there a lot.",
    "cat3_global": "Roam because my family is from there.Europ because my family is from there.",
    "cat4_aspirational": "cuba because its hot. iceland because its cold.",
    "cat5_music": "the song little sally walker takes me back to grade 3 with my best friend.",
    "youtube_url": ""
  },
  {
    "timestamp": "9/3/2026 13:47:54",
    "raw_name": "Maia",
    "matched_name": "Maia Rendell",
    "pin": "MAR",
    "class": "903",
    "cat1_personal": "Gwenna's house, Gwenna's home feels very special to me. I feel welcome when I walk in and reno greets me. I also enjoy me and Ollies foot fives.",
    "cat2_community": "Fundy scoops,I really like going to Fundy scoops. Me and Gwenna have many memories there and made multiple friends.",
    "cat3_global": "",
    "cat4_aspirational": "Europe. I want to go to Europe so bad. It has so many cool places to visit and tourist spots.",
    "cat5_music": "Bonnie Tyler - Holding Out For A Hero (Official HD Video)\n\nYouTube \u00b7 Bonnie Tyler\n320.3M+ views \u00b7 10 years ago\nhttps://www.youtube.com/watch?v=6JCLY0Rlx6Q\n\nThese songs link back to many memories !",
    "youtube_url": "https://www.youtube.com/watch?v=6JCLY0Rlx6Q"
  },
  {
    "timestamp": "9/3/2026 13:50:40",
    "raw_name": "gwenna",
    "matched_name": "Gwenna White",
    "pin": "GWW",
    "class": "903",
    "cat1_personal": "maias house, winnie is super cute and ms.rendell is very wolcoming to me and her loft is super cute.",
    "cat2_community": "halifax shopping center,i love to shop and my favorite hobbie is shopping and the best part about this mall is that it hasd a aritzia.aritzia is my happy place and i love it.",
    "cat3_global": "irerland, my moms mom is from ierland but she was just born there shes dosent actualy have any irish in her.me  my mom and my brother went there and visites my grandmothers house.",
    "cat4_aspirational": "italy i just think it would be a wonderfull trip i wanna go super bad.",
    "cat5_music": "eye of the tiger by katy perry in pre primary we always listend to it",
    "youtube_url": ""
  },
  {
    "timestamp": "9/3/2026 13:52:19",
    "raw_name": "Zoe",
    "matched_name": "Zoe Muise",
    "pin": "ZEM",
    "class": "903",
    "cat1_personal": "My house because ive lived there my whole life and so many of my memorys have been made in that house. My parents have lived there for around 20 years and theyve helped me make so many memorys there aswell. \n\nBicentennial school because ive been here for 10 years now and ive met all my friends here. Over the years ive had many great teachers and ive made many great friends while being here.",
    "cat2_community": "The mall because I hang out there with friends all the time and I really enjoy shopping there aswell.\n\nBeasley feild because thats where my track team trains in the summer and fall. Ive trained there for so many years and I love being there.",
    "cat3_global": "England. My mom is from there and every two years me, my mom, and sometimes my dad go over there to viset family and see the sights.\n\nYarmouth Nova Scotia because thats where my dad is from and we always go see my grandma at christmas.",
    "cat4_aspirational": "Hawaii, Ive really wanted to go to Hawaii for so long because it seems so warm and fun to travel to.\n\nLos Angeles. I really want to go there because thats where Billie eilish is and it would be really fun to see her in concert. The weather also seems really nice and the beaches look super nice.",
    "cat5_music": "https://www.youtube.com/watch?v=ru0K8uYEZWw&themeRefresh=1\nThe song Cant stop the feeling by Justin Timberlake because it used to be my favorire song and in grade 1 and my music teacher used to play it all the time.",
    "youtube_url": "https://www.youtube.com/watch?v=ru0K8uYEZWw"
  },
  {
    "timestamp": "9/3/2026 13:53:12",
    "raw_name": "Oli Salcedo",
    "matched_name": "Oli Salcedo",
    "pin": "",
    "class": "903",
    "cat1_personal": "Cowbay when my parents first got divorced my dad moved there and it was a nice change.\nEast Coast Varcity Ive played soccer there almost my whole life and i love soccer",
    "cat2_community": "Mic Mac mall because I go there so much and I know a lot of the workers and every one is super nice. Sullivans pond I love how the geese can just do what ever they want and no one cares.",
    "cat3_global": "Well my dad was born in venezuela and he makes my family venezuelan food like adepas sometimes. My mom and my dad met in Jamacia and my dad has a lot of storys from his visit.",
    "cat4_aspirational": "I would love to go to Tokyo Japan because I love the culture there and the veiws are pretty nice. I would like to visit alberta because over summer i went to a sleep away camp for about 20 days and a lot of my friends from it live there and i miss them a lot",
    "cat5_music": "The first technoligy me and my brother ever had was a super tiny music player and my favourite song was guns N'Roses \"Live And Let Die\"\n\nhttps://www.youtube.com/watch?v=iXKVA5Xs90M&list=RDiXKVA5Xs90M&start_radio=1",
    "youtube_url": "https://www.youtube.com/watch?v=iXKVA5Xs90M"
  },
  {
    "timestamp": "9/3/2026 13:53:39",
    "raw_name": "Callum MacDonald",
    "matched_name": "Callum MacDonald",
    "pin": "CMA",
    "class": "903",
    "cat1_personal": "wolfvillie because me and my old basketball team played a torment there and it was fun.\n my house because i have lots of good memory's there",
    "cat2_community": "the wave in Halifax because it was fun to climb.\nfindly center because i played basketball with my friends there a lot.",
    "cat3_global": "Cape Breton because all my family lives there.\nToronto because some of my cousins live there.",
    "cat4_aspirational": "Europe because it looks cool.\nand England because i wanna see the big Ben",
    "cat5_music": "https://www.youtube.com/watch?v=SlCXgj2bS_A \nthis song because i use to listen to it at my cottage",
    "youtube_url": "https://www.youtube.com/watch?v=SlCXgj2bS_A"
  },
  {
    "timestamp": "9/3/2026 13:56:01",
    "raw_name": "Patience",
    "matched_name": "Patience Sampson",
    "pin": "PSA",
    "class": "903",
    "cat1_personal": "My first landmark would be Highfield Park, because that's where my Nan, Mom, and all me and my siblings grew up.\n\nMy bed has lots of memories including me sleeping and sleepovers and family friends chilling on it.",
    "cat2_community": "My Nan likes to take me and my sibling to the Cole Harbour Pool, so thats my first choice.\n\nMy second choice would have to be school because I've made a good amount of my friends here.",
    "cat3_global": "One side of my family is from Cape Breton and they are purely Caucasian and we go down once every 2 years to spend time with cousins and they have a really cute dog named Hunter.\n\nThe other side of my family lives in Virginia, Norfolk, and Washington. DC so the trips down there are pretty fun because Nova Scotia can get pretty boring.",
    "cat4_aspirational": "I want to go to Philippines because of the weather (not in spring) and I like their foods.\n\nI also wanna go to Germany because of the Neuschwanstein Castle, which I did a project on in tech ed last year!",
    "cat5_music": "Hotel California is a good song for me to chose because my Nan introduced it to me when I was pretty young, and everytime I hear it I think of her.\n\nEagles - Hotel California (Official Audio)\nYouTube \u00b7 Eagles\nMar 25, 2025",
    "youtube_url": ""
  },
  {
    "timestamp": "9/3/2026 13:56:05",
    "raw_name": "Liam MacLean",
    "matched_name": "Liam MacLean",
    "pin": "AAM",
    "class": "903",
    "cat1_personal": "A place that hold a special meaning to me is my home because it is where I have lived my entire life and where I keep all of my belongings. Another place that holds a special meaning to me is my paddling club Senobe. This place is special to me because it is where I have been paddling for many years and where ive made lots of friends.",
    "cat2_community": "Crichton Park school is important to me because it was the elementary school I went to and where I made most of my friends that I have today. Banook lake is significant to me because it is the lake I have paddled and trained on for most of my life.",
    "cat3_global": "Nova scotia because it is where me and my parents were born.",
    "cat4_aspirational": "I want to go to Niagra fall some day because it looks super cool and I have never seen any big waterfalls in person. I would like to go to Canadas wonderland because I want to go on the huge rollercoasters.",
    "cat5_music": "https://www.youtube.com/watch?v=GcYVCvBq0FY",
    "youtube_url": "https://www.youtube.com/watch?v=GcYVCvBq0FY"
  },
  {
    "timestamp": "9/3/2026 13:56:54",
    "raw_name": "Misha Coronel",
    "matched_name": "Misha Kaplin",
    "pin": "MSK",
    "class": "802",
    "cat1_personal": "Two locations that hold a special meaning to me are Toronto and the Philippines. The Philippines is where I grew up which is my hometown. I made a lot of memories there and it really feels like home. Toronto was where I used to live and made a lot of connections. I went there this summer and met with my friends.",
    "cat2_community": "My house and my aunt's house are two places I like at most. I like my home since I can just be comfortable. I like being at home because I don't like being outside. I also like my aunt's house since it's the same as my home. I like being there because my family spends a lot of quality time.",
    "cat3_global": "Kuwait was where I used to live for a while when I was younger. I liked it there because it was really peaceful. I'd say it's the same for Nova Scotia, I like it here because it's also pretty chill.",
    "cat4_aspirational": "I really want to live in South Korea one day. I like their culture and I wanna study there. I also want to visit Japan since my cousins live there. I also want to experience how they live there.",
    "cat5_music": "https://youtu.be/xy3AcmW0lrQ?si=2Z7KXWaZfiMagzPG",
    "youtube_url": "https://youtu.be/xy3AcmW0lrQ"
  },
  {
    "timestamp": "9/3/2026 13:57:16",
    "raw_name": "Avery Fisher",
    "matched_name": "Avery Peters",
    "pin": "AVP",
    "class": "901",
    "cat1_personal": "My old house, it's where my parents and I lived for a long time with my cat. London because my parents liver there for two years and I recently saw it for the first time.",
    "cat2_community": "The Dartmouth common because I grew up playing golf and base ball there. This school because I've gone here since I was born.",
    "cat3_global": "My cottage because my great grandfather built it along time ago and multiple generations have went there. The Scandinavian Countries because my family are from there.",
    "cat4_aspirational": "Findland in 2 years because the World Junoirs are hosted there. Germany because I love learning about WW2.",
    "cat5_music": "https://www.youtube.com/watch?v=IFu5Dr6drF8 and https://www.youtube.com/watch?v=uXLOa83-fUA . Both of these songs are played every year at my cottage.",
    "youtube_url": "https://www.youtube.com/watch?v=IFu5Dr6drF8"
  },
  {
    "timestamp": "9/3/2026 13:58:41",
    "raw_name": "Pauline C. Samillano",
    "matched_name": "Sam Harrison",
    "pin": "SHA",
    "class": "802",
    "cat1_personal": "My house, holds so many memories that will always be tied to me no matter what. Though there were times when something shouldn't be kept in my mind, I personally think that's what makes a home, a home. Not to mention the good times I've had with others in my home. \n\nSchool, It may not be something I always look forward to, but the memories that I make here, is something I could never relive. All of the times when I was with my friends, teachers, and just being here, makes me realize that this is a one time thing, and I should take every moment for granted.",
    "cat2_community": "The Commons, just being with my family, and friends there, always makes such good memories. And I enjoy every second and minute when I'm there. \n\nThe Mic Mac Mall, always going there will unlock memories I've kept in the back of my mind and have forgotten about it. Makes me feel really nostalgic when I go through each area of the place.",
    "cat3_global": "Saudi Arabia, I was born here, which would make sense with all of the older memories I've made with others. Whenever I get reminded of the place I would never forget, it always makes me feel really nice. \n\nThe Philippines, though I've never been there for long, even when I'm from there. I remember all the people I've met that I haven't seen in so long nowadays, always makes miss them a lot! Especially the place I was living at that time.",
    "cat4_aspirational": "South Korea, all of the food I've seen from there, makes my stomach grumble every time, and the place just looks gorgeous from the pictures I've seen before.\n\nGermany, I've dreamed about going there, as I don't have much information about the place. I've always wanted to learn the language as it really interest me.",
    "cat5_music": "High Hopes by Panic! At the disco, always hearing it on social media, or even on the radio always makes me think about the older memories I've created, and not to mention, it was my favorite song of all time before I started to grow older and older.",
    "youtube_url": ""
  },
  {
    "timestamp": "9/3/2026 13:58:46",
    "raw_name": "Zeiden Sampang",
    "matched_name": "Sam Harrison",
    "pin": "SHA",
    "class": "802",
    "cat1_personal": "My first location would be my first apartment that I had moved away from in February of 2020.\nI lived there for eight years and had made so many memories with my parents and brothers. Me and my brothers would always play games together on a Wii in the living room and it had made so many good memories.\n\nMy second location would be my cousin's house.\nI've had a lot of family parties there and also spent time with a lot of my family during the holidays.",
    "cat2_community": "Bicentennial School is my choice for a local community location.\nI chose Bicentennial School because of how many friends I made, meeting great teachers, and learning a lot of cool things.\n\nMy second community location is",
    "cat3_global": "The Philippines is one of my global locations.\nI've only gone there a few times to visit family but every time I go there I spend a lot of time with that family doing a lot of fun things. Just last year I went bowling, swimming, I took a lot of walks and a lot more. Being there is so fun whenever I get the chance.",
    "cat4_aspirational": "I'd like to go to LA because of how nice it looks and its weather. It also looks very fun to be there with how much freedom and activity you can do.",
    "cat5_music": "Whenever I play les by Childish Gambino I think of my old house because of how much it was played there by my brothers.",
    "youtube_url": ""
  },
  {
    "timestamp": "9/3/2026 13:59:21",
    "raw_name": "Oscar Donaldson",
    "matched_name": "Oscar Pinks",
    "pin": "SCP",
    "class": "902",
    "cat1_personal": "There was a mermorial back sometime before July that was held for my great grandfather in England, reconizing the roll that he played in WW2. Im not actually sure if he has a monument dedacated to him, but I dont have any other ideas.\n\nSecond is my house, because I dont have any ideas left, nothing that is significant",
    "cat2_community": "I think one is this school, because I've gone here for 10 years, no other schoool, and I've had a great time (almost) every year\n\nand maybe Cole Harbour, because my uncle played AAA hocket there growing up, and I'm from Dartmouth so I respect them as hokcey adversaries",
    "cat3_global": "I think Kent, England is a significant place because my granparents live there\n\nAnd also London, England because my dad is from there",
    "cat4_aspirational": "I think I would like to visit Tampa Bay to see a Tampa Bay Lightning game (Once Trump isn't president)\n\nMaybe Portugal, because a lot of my family also wants to see it, and i've never been",
    "cat5_music": "We were once down on my great uncles warf, by the see, and where fishing for crabs, and my dad cept playing \"Crabs In The Bucket\"\n\nI dont know who its by, sorry",
    "youtube_url": ""
  },
  {
    "timestamp": "9/3/2026 13:59:54",
    "raw_name": "Tommy",
    "matched_name": "Tommy MacInnes",
    "pin": "TMM",
    "class": "903",
    "cat1_personal": "Wolfville. Me and my family go up to wolfville every year to go apple picking.",
    "cat2_community": "A place in my local community that is significant to me would be peggys cove. Me and my family love going to peggys cove and climbing the rocks. Rainbow haven beach. I love rainbow haven because i like swimming in the ocean and i hangout with freinds there.",
    "cat3_global": "Scotland and Ireland. My mom side is from Ireland, she moved here when she was 13. And my dads side is from Scotland but he has lived in canada since he was 3.",
    "cat4_aspirational": "I would love to go to Switzerland because it looks beautiful there on the moutains. I would also love to go to Italy. I would like to go to Italy because of all the good food.",
    "cat5_music": "I dont have a specific song but my dads favorite musican was bruce springsteen and I remember his music since I was very young.",
    "youtube_url": ""
  },
  {
    "timestamp": "9/3/2026 14:01:18",
    "raw_name": "April Flaherty",
    "matched_name": "April Flaherty",
    "pin": "APA",
    "class": "903",
    "cat1_personal": "The Pointe du chien warf is a special sopt to me because every year I go there with my family. I have been going to the Pointe du chien warf since I was a baby. \n\nBanook Canoe Club is another special spot for me because when I was younger I went and paddled ther every summer.",
    "cat2_community": "Basinview Drive Community School in Bedford, I go there all the time for dance compotitions.\n\nCrichton Park elementry school was my elementry school. I spent a lot of time there.",
    "cat3_global": "Sharbot Lake in Ontario has been in my family for so many years. I go there every summer and I have been going there since I was born.\n\nIerland, my familys haritage comes from Ierland.",
    "cat4_aspirational": "I want to go to Flahertys irish pub in Ierland, I am a Flaherty. I think it would be really cool to go there. \n\nI want to go to Scotland and do the world championship for highland dance.",
    "cat5_music": "https://www.youtube.com/watch?v=c6rP-YP4c5I\n\nMy grade 1 teacher would play this song every day at the end of the day.",
    "youtube_url": "https://www.youtube.com/watch?v=c6rP-YP4c5I"
  },
  {
    "timestamp": "9/3/2026 14:02:26",
    "raw_name": "Ava Giacomantonio",
    "matched_name": "Ava Giacomantonio",
    "pin": "AVG",
    "class": "903",
    "cat1_personal": "Cottage: My moms family has owned a cottage in Pictou for 55 years. It doesn't hold one specific memory, but I can remember going there for around a month of every summer since I could remember and it's a happy place.\n118 Highway: During covid my dad and stepmom realised we were finishing our school work quickly so they decided to make their own classes to keep us busy. I have a very vivid memory of my dad making me and my siblings act like we were military marching down the 118 for phys ed.",
    "cat2_community": "Shubie Park: This is my favorite place to take a brain break and walk my dogs.\nLake Banook. Kayaking is my favorite sport. I do year round training with some of my best friends and make my best memories at Banook.",
    "cat3_global": "Italy: My entire dads side is Italian. Every christmas we go to my great uncles houses that they decorate in ALOT of lights and eat a bunch of homeade Italian food.\nThe lobster in Shediac: We take photos at the big lobster in Shediac anually. We hang many of the photos in our house.",
    "cat4_aspirational": "Seoul: I love the korean culture, food and people so I have books and dictionaries all based around South Korea. I really love ramen...\nLucky Bay: I really want to go to this beach in Australia because I heard it was the most beautiful. It seems simmilar to Bondi beach, but less people.",
    "cat5_music": "https://www.youtube.com/watch?v=sYfmQ5eAQlg",
    "youtube_url": "https://www.youtube.com/watch?v=sYfmQ5eAQlg"
  },
  {
    "timestamp": "9/3/2026 14:03:14",
    "raw_name": "Evan Smith",
    "matched_name": "Evan Smith",
    "pin": "EVS",
    "class": "903",
    "cat1_personal": "1. My home. I've been living there for 6 years, and I have made countless memories while living here.\n2. Bihi. There have been ups and downs, but what is life without highs and lows?",
    "cat2_community": "1. Mic Mac Mall. I go there every once in a while and always have a great time.\n2. The Bridge Terminal. It's very convenient for me to get around the city, and I like it because of that.",
    "cat3_global": "1. Scotland, I think? I'm pretty sure some of my family came from there, but I'm not sure.\n2. Ireland. Similar to Scotland, I don't really know where my family's background is from. It's been a while.",
    "cat4_aspirational": "1. Singapore Changi Airport. If you see the photos of it, it genuinely looks like the 8th Wonder Of The World. \n2. Toronto. I've had enough time to truly experience it, only stops at Pearson and 2-day trips.",
    "cat5_music": "Unfortunately, I don't really have a song that really connects to my life before third grade. I wasn't a big music guy when I was younger, so I don't have an authentic answer to this that wouldn't feel like lying.",
    "youtube_url": ""
  },
  {
    "timestamp": "9/3/2026 14:03:20",
    "raw_name": "Ben Fost",
    "matched_name": "Ben Veach",
    "pin": "BEV",
    "class": "803",
    "cat1_personal": "The Wave, and My house. The wave I have many good memories of climbing, even though they say don't climb it. And my house holds memories of me learning guitar, funny memories, and good memories.",
    "cat2_community": "Sportsplex, and Camp Kidston. Sportsplex is the place I go to improve and better myself, it makes me feel happy because of that. And Camp Kidston, don't even get me started, that place is my second home, most of the friend I have made have come from that place, its always welcoming and loving towards anybody who comes, I have only good memories from that place, and only good friends.",
    "cat3_global": "Newfoundland, And England. Newfoundland is where my father was born, we visited it a couple of years ago so that me and my sister could learn about how my father grew up. Same applies to my mother and her roots in england.",
    "cat4_aspirational": "Paris, and Portugal. Paris is pretty obvious, its the best tourist attraction in the world with the Eiffel Tower. And Portugal is because of the food, the places, and the beauty of it.",
    "cat5_music": "https://www.youtube.com/watch?v=L_jWHffIx5E Smash Mouth- All Star",
    "youtube_url": "https://www.youtube.com/watch?v=L_jWHffIx5E"
  },
  {
    "timestamp": "9/3/2026 14:04:38",
    "raw_name": "Addy Crawford",
    "matched_name": "Addy Crawford",
    "pin": "ADC",
    "class": "903",
    "cat1_personal": "My old house is special to me because I grew up there and have so many good and bad memories there.\n\nMy elementary school music teachers room. His room is a core memory because he introduced me to great music and made me fine my love in music. I have always visted him to talk about music.",
    "cat2_community": "Forest road: Forest Road is the street I grew up on. It has a special meaning to me because when I was younger I knew everyone and was very social with the neigbours which gave me some of the most memories.\n\n The old Sportsplex: Sportsplex holds a memory of when I was younger and would constantly be there with my dad.",
    "cat3_global": "Ireland is apart of my dad's culture because, it's where my dad's father is from and most family on that side.\n\nCape breaton is where most of my moms side of the family is and we are lucky to visit often.",
    "cat4_aspirational": "Somewhere in Nothern Italy I really want to go there because one of my favorite movies was filmed there and I'd love to visit\n\nI really want to go to England with my grandparents because they've gone every year and Ive always wanted to go with them to see all kinds of cool stores.",
    "cat5_music": "I'll belive in anything by Wolf Parade is my favourite song and is rooted in me. This song means so much to me and reminds me of how lucky I am to have supportive family and friends.",
    "youtube_url": ""
  },
  {
    "timestamp": "9/3/2026 14:06:05",
    "raw_name": "Zana Shala",
    "matched_name": "Zana Shala",
    "pin": "ZAS",
    "class": "903",
    "cat1_personal": "My grandmothers, house in Kosovo. The reason why, is because I remember going there with  all of my cousins when we were kids, and it was just a very special and important time that I still think about.",
    "cat2_community": "The mall. I have meet so many  new people ther and have made so many memories.\nAddys house. Me andaddy have made so many memories there, and i spend so much time there it feels like my second home.",
    "cat3_global": "Pristina, Kosovo. The reasoning behind why i chose Pristina is because this is where me and my entire family is from. Its a very special place to me and I visit it everysingle summer.\nMy aunts house. I still find my aunts house very special to my persanal family because when we first moved to Canada we spent majority of our time there learing, and meeting new peaole. We still go there very often for holidays, birthdays, or  special days.",
    "cat4_aspirational": "the Lombardy region of Northern Italy. I really want to go there because my favoirite movie, Call  me by your name was filmed there, and it just looks like such a beatiful place.\nI also really want to go to new york, because so many movies that I really enjoy were filmed there, and it just looks llike such a magical  place, but i mostly want to  go there during the winter.",
    "cat5_music": "The song that reminds me of a special moment is the song Freak. Everytime i listen to it, it reminds me of when i was in grade 5, and i listened to it almost every single day.\nhttps://www.youtube.com/watch?v=NfMegACVJQw",
    "youtube_url": "https://www.youtube.com/watch?v=NfMegACVJQw"
  }
];
