#!/usr/bin/env python3
"""Roster privacy split for the bihi2027 Pages site.

The public site may only carry names-only roster data (first_name, last_name,
homeroom, grade, courses, course_label). PINs, student IDs, usernames and full
legal first names stay local (Private_Student_Data/) and reach the GAS via the
set_roster action (Script Property ROSTER_PRIVATE).

Source of truth: Student_System/students_roster_data.js (kept current with
adds/renames; generate_roster.py's raw_data has drifted behind it).

Usage:
  python tools/roster_privacy.py --check          # report only, no writes
  python tools/roster_privacy.py --emit           # write all outputs
  python tools/roster_privacy.py --emit --drop-pin  # public JS loses pin too
"""
import argparse
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROSTER_JS = os.path.join(ROOT, "Student_System", "students_roster_data.js")
PRIVATE_DIR = os.path.join(ROOT, "Private_Student_Data")
FULL_JSON = os.path.join(PRIVATE_DIR, "roster_full.json")
GAS_PAYLOAD = os.path.join(PRIVATE_DIR, "roster_gas_payload.json")

# Fields allowed in the PUBLIC (deployed) roster file.
PUBLIC_FIELDS = ["homeroom", "grade", "first_name", "last_name", "courses",
                 "course_label"]
# Fields that must never be public once Phase 2 lands (pin dropped last).
PRIVATE_FIELDS = ["student_id", "username", "full_first_name"]


def load_roster():
    with io.open(ROSTER_JS, encoding="utf-8") as f:
        src = f.read()
    prefix = "window.MASTER_ROSTER_DATA = "
    idx = src.find(prefix)
    if idx == -1:
        sys.exit("unexpected roster JS header: %r" % src[:60])
    return json.loads(src[idx + len(prefix):].strip().rstrip(";").strip())


def public_record(rec, drop_pin):
    keep = list(PUBLIC_FIELDS) + ([] if drop_pin else ["pin"])
    out = {}
    for key in keep:
        if key in rec:
            out[key] = rec[key]
    leaked = [k for k in rec if k not in keep and k not in ("pin",)]
    return out, leaked


def write_roster_js(records, drop_pin):
    lines = ["// students_roster_data.js — NAMES-ONLY roster for public Pages use.",
             "// Generated by tools/roster_privacy.py — do not hand-edit.",
             "// PINs / student IDs / usernames / legal names live in",
             "// Private_Student_Data/ (never committed) and in the GAS roster property.",
             "window.MASTER_ROSTER_DATA = ["]
    for i, rec in enumerate(records):
        pub, _ = public_record(rec, drop_pin)
        blob = json.dumps(pub, ensure_ascii=False)
        lines.append("  " + blob + ("," if i < len(records) - 1 else ""))
    lines.append("];")
    with io.open(ROSTER_JS, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


def write_private_outputs(records):
    os.makedirs(PRIVATE_DIR, exist_ok=True)
    with io.open(FULL_JSON, "w", encoding="utf-8", newline="\n") as f:
        json.dump(records, f, ensure_ascii=False, indent=2)
        f.write("\n")
    payload = {
        "updated": "",
        "students": [
            {
                "pin": rec["pin"],
                "hr": rec["homeroom"],
                "first": rec["first_name"],
                "last": rec["last_name"],
                "grade": rec["grade"],
            }
            for rec in records
        ],
        # Typed variants the server should accept as their canonical pin.
        # Ported from api.js / Class_Opening_Slide special cases.
        "aliases": {"SHA": "SAH"},
    }
    with io.open(GAS_PAYLOAD, "w", encoding="utf-8", newline="\n") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write("\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only")
    ap.add_argument("--emit", action="store_true", help="write outputs")
    ap.add_argument("--drop-pin", action="store_true",
                    help="public JS also loses pin (Phase 2 final step)")
    args = ap.parse_args()

    records = load_roster()
    seen_pins = {}
    dupes = []
    missing = []
    for rec in records:
        pin = rec.get("pin")
        if not pin:
            missing.append("%s, %s" % (rec.get("last_name"), rec.get("first_name")))
        elif pin in seen_pins:
            dupes.append((pin, seen_pins[pin], rec["last_name"]))
        else:
            seen_pins[pin] = rec["last_name"]
    print("records: %d | missing pin: %d | duplicate pins: %d"
          % (len(records), len(missing), len(dupes)))
    if missing:
        print("  missing:", missing)
    if dupes:
        print("  dupes:", dupes)
    sample, leaked_now = public_record(records[0], args.drop_pin)
    print("public fields would be: %s" % sorted(sample))
    if args.emit:
        write_private_outputs(records)
        write_roster_js(records, args.drop_pin)
        print("wrote: %s, %s, %s (drop_pin=%s)"
              % (ROSTER_JS, FULL_JSON, GAS_PAYLOAD, args.drop_pin))


if __name__ == "__main__":
    main()
